#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require_relative 'lexer'
require_relative 'clasesParser'

class ErrorSintactico < RuntimeError

	def initialize(token)
		@token = token
	end

	def to_s
		"fila: " + @token.fila.to_s() + ", columna: " + @token.columna.to_s() + ", token inesperado: #{@token.token} \n"   # EL PROBLEMA ES ACA
	end
end

class ParserRtn < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 246)
	
	def initialize(tokens)
		@tokens = tokens
		@yydebug = true
		super()
	end 

	def parse
		do_parse
	end

	def next_token
		#puts @tokens
		@tokens.shift
	end

	def on_error(id, token, pila)
		raise ErrorSintactico.new(token)
	end
	
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    80,    71,    11,    67,    80,    71,    11,    67,     7,    75,
     6,    68,    71,    11,    67,    68,    80,    71,    11,    67,
    74,    66,    68,    90,   144,    66,     5,    68,    86,   145,
   123,    87,    66,   124,    71,    11,    67,    66,    44,    21,
    22,    71,    11,    67,    68,    13,    14,     5,    72,    73,
    11,    68,    72,    73,    66,     6,    71,    11,    67,    72,
    73,    66,    21,    22,    72,    73,    68,    71,    11,    67,
    71,    11,    67,    71,    11,    67,    66,    68,    21,    22,
    68,    72,    73,    68,    21,    22,    15,    66,    72,    73,
    66,    21,    22,    66,    21,    22,    71,    11,    67,    16,
    17,    47,    48,    72,    73,    11,    68,    54,    55,    71,
    11,    67,    56,    57,    72,    73,    66,    72,    73,    68,
    72,    73,    71,    11,    67,    71,    11,    67,    58,    66,
   114,    59,    68,    60,    61,    68,    11,    11,    71,    11,
    67,    88,    66,    72,    73,    66,    11,    92,    68,    74,
    93,    71,    11,    67,    75,   116,    72,    73,    66,   116,
   118,    68,   125,    11,    71,    11,    67,   153,   165,    72,
    73,    66,    72,    73,    68,   168,   169,    71,    11,    67,
    71,    11,    67,   173,    66,    72,    73,    68,   178,   182,
    68,   nil,   nil,    71,    11,    67,   nil,    66,    72,    73,
    66,   nil,   nil,    68,   nil,   nil,    71,    11,    67,   nil,
   nil,    72,    73,    66,   nil,   nil,    68,   nil,   nil,    71,
    11,    67,   nil,   nil,    72,    73,    66,    72,    73,    68,
   nil,   nil,    71,    11,    67,    71,    11,    67,   nil,    66,
    72,    73,    68,   nil,   nil,    68,   nil,   nil,    71,    11,
    67,   nil,    66,    72,    73,    66,   nil,   nil,    68,   nil,
   nil,    71,    11,    67,   nil,   nil,    72,    73,    66,   nil,
   nil,    68,   nil,   nil,    71,    11,    67,   nil,   nil,    72,
    73,    66,    72,    73,    68,   nil,   nil,    71,    11,    67,
    71,    11,    67,   nil,    66,    72,    73,    68,   nil,   nil,
    68,   nil,   nil,    71,    11,    67,   nil,    66,    72,    73,
    66,   nil,   nil,    68,   nil,   nil,    71,    11,    67,   nil,
   nil,    72,    73,    66,   nil,    11,    68,    94,    95,    96,
    97,    98,   nil,   nil,    72,    73,    66,    72,    73,    94,
    95,    96,    97,    98,   nil,   nil,   nil,    11,    34,   nil,
    72,    73,    13,    14,    35,   nil,    37,    38,    39,    40,
   nil,   nil,    41,    72,    73,   nil,    42,   nil,    43,    52,
    34,    11,   nil,   nil,    13,    14,    35,   nil,    37,    38,
    39,    40,   nil,   nil,    41,   nil,   nil,   nil,    42,   nil,
    43,   nil,    11,   nil,    34,   nil,   nil,   nil,    13,    14,
    35,   nil,    37,    38,    39,    40,   nil,   nil,    41,    11,
   nil,   nil,    42,   nil,    43,    34,   nil,   nil,   nil,    13,
    14,    35,   nil,    37,    38,    39,    40,   nil,    11,    41,
   nil,   nil,    34,    42,   nil,    43,    13,    14,    35,   nil,
    37,    38,    39,    40,   nil,    11,    41,   nil,   nil,   nil,
    42,    34,    43,   nil,   nil,    13,    14,    35,   nil,    37,
    38,    39,    40,   nil,   nil,    41,   nil,    11,    34,    42,
   nil,    43,    13,    14,    35,   nil,    37,    38,    39,    40,
   nil,   nil,    41,   nil,    11,   nil,    42,   nil,    43,   152,
    34,   nil,   nil,   nil,    13,    14,    35,   nil,    37,    38,
    39,    40,   nil,   nil,    41,   nil,    11,    34,    42,   nil,
    43,    13,    14,    35,   nil,    37,    38,    39,    40,   nil,
   nil,    41,   nil,    11,   nil,    42,   nil,    43,   157,    34,
   nil,   nil,   nil,    13,    14,    35,   nil,    37,    38,    39,
    40,   nil,   nil,    41,   nil,   160,    34,    42,    11,    43,
    13,    14,    35,   nil,    37,    38,    39,    40,   nil,   161,
    41,   nil,   nil,   nil,    42,    11,    43,   nil,   nil,   nil,
   163,    34,   nil,   nil,   nil,    13,    14,    35,   nil,    37,
    38,    39,    40,   nil,    11,    41,   nil,   164,    34,    42,
   nil,    43,    13,    14,    35,   nil,    37,    38,    39,    40,
   nil,    11,    41,   nil,   nil,   nil,    42,    34,    43,   nil,
   nil,    13,    14,    35,   nil,    37,    38,    39,    40,   nil,
    11,    41,   nil,   167,    34,    42,   nil,    43,    13,    14,
    35,   nil,    37,    38,    39,    40,   nil,    11,    41,   nil,
   nil,   nil,    42,    34,    43,   nil,   nil,    13,    14,    35,
   nil,    37,    38,    39,    40,   nil,    11,    41,   nil,   172,
    34,    42,   nil,    43,    13,    14,    35,   nil,    37,    38,
    39,    40,   nil,    11,    41,   nil,   nil,   nil,    42,    34,
    43,   nil,   nil,    13,    14,    35,   nil,    37,    38,    39,
    40,   nil,   nil,    41,   nil,   175,    34,    42,    11,    43,
    13,    14,    35,   nil,    37,    38,    39,    40,   nil,   nil,
    41,   nil,   nil,   nil,    42,    11,    43,   nil,   nil,   nil,
   179,    34,   nil,   nil,   nil,    13,    14,    35,   nil,    37,
    38,    39,    40,   nil,   nil,    41,   nil,    11,    34,    42,
   nil,    43,    13,    14,    35,   nil,    37,    38,    39,    40,
   nil,   nil,    41,   nil,    11,   nil,    42,   nil,    43,   184,
    34,   nil,   nil,   nil,    13,    14,    35,   nil,    37,    38,
    39,    40,   nil,   nil,    41,   nil,    11,    34,    42,   nil,
    43,    13,    14,    35,   nil,    37,    38,    39,    40,   nil,
   nil,    41,   nil,   nil,   nil,    42,   nil,    43,   186,    34,
   nil,   nil,   nil,    13,    14,    35,   nil,    37,    38,    39,
    40,   nil,   nil,    41,   nil,   nil,   nil,    42,   nil,    43,
    94,    95,    96,    97,    98,    99,   100,   101,   102,   103,
   104,   105,   106,   107,   108,    94,    95,    96,    97,    98,
    99,   100,   101,   102,   103,   104,   105,   106,   107,   108,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   119,
   177,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   176,    94,    95,    96,    97,    98,    99,   100,
   101,   102,   103,   104,   105,   106,   107,   108,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   nil,   nil,   nil,   nil,   nil,   nil,   162,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   117,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   120,    94,    95,    96,
    97,    98,    99,   100,   101,   102,   103,   104,   105,   106,
   107,   108,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   183,    94,    95,    96,    97,    98,    99,   100,
   101,   102,   103,   104,   105,   106,   107,   108,   nil,   nil,
   143,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,    94,    95,    96,    97,
    98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
   108,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,    94,    95,    96,    97,
    98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
   108,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,    94,    95,    96,    97,
    98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
   108,    94,    95,    96,    97,    98,    99,   100,   101,   102,
   103,   104,   105,   106,   107,    94,    95,    96,    97,    98,
    99,   100,   -82,   -82,   -82,   -82,   -82,   -82,    94,    95,
    96,    97,    98,    99,   100,   -82,   -82,   -82,   -82,   -82,
   -82,    94,    95,    96,    97,    98,    99,   100,   -82,   -82,
   -82,   -82,   -82,   -82,    94,    95,    96,    97,    98,    99,
   100,   -82,   -82,   -82,   -82,   -82,   -82,    94,    95,    96,
    97,    98,    99,   100,   -82,   -82,   -82,   -82,   -82,   -82,
    94,    95,    96,    97,    98,    99,   100,   -82,   -82,   -82,
   -82,   -82,   -82,    94,    95,    96,    97,    98,    99,   100,
   101,   102,   103,   104,   105,   106 ]

racc_action_check = [
    38,    38,    38,    38,    39,    39,    39,    39,     1,    36,
     2,    38,    35,    35,    35,    39,   116,   116,   116,   116,
    36,    38,    35,    48,   115,    39,     4,   116,    44,   115,
    88,    44,    35,    88,    40,    40,    40,   116,    16,    48,
    48,    42,    42,    42,    40,     6,     6,     0,    38,    38,
     5,    42,    39,    39,    40,     0,    43,    43,    43,    35,
    35,    42,    16,    16,   116,   116,    43,    66,    66,    66,
    67,    67,    67,    68,    68,    68,    43,    66,    13,    13,
    67,    40,    40,    68,    87,    87,     7,    66,    42,    42,
    67,   124,   124,    68,   125,   125,    74,    74,    74,    10,
    12,    17,    18,    43,    43,    20,    74,    25,    26,    75,
    75,    75,    27,    28,    66,    66,    74,    67,    67,    75,
    68,    68,    94,    94,    94,    95,    95,    95,    29,    75,
    75,    30,    94,    31,    33,    95,    37,    41,    96,    96,
    96,    45,    94,    74,    74,    95,    46,    49,    96,    51,
    52,    97,    97,    97,    65,    77,    75,    75,    96,    81,
    83,    97,    89,    92,    98,    98,    98,   122,   152,    94,
    94,    97,    95,    95,    98,   155,   157,    99,    99,    99,
   100,   100,   100,   167,    98,    96,    96,    99,   172,   179,
   100,   nil,   nil,   101,   101,   101,   nil,    99,    97,    97,
   100,   nil,   nil,   101,   nil,   nil,   102,   102,   102,   nil,
   nil,    98,    98,   101,   nil,   nil,   102,   nil,   nil,   103,
   103,   103,   nil,   nil,    99,    99,   102,   100,   100,   103,
   nil,   nil,   104,   104,   104,   105,   105,   105,   nil,   103,
   101,   101,   104,   nil,   nil,   105,   nil,   nil,   106,   106,
   106,   nil,   104,   102,   102,   105,   nil,   nil,   106,   nil,
   nil,   107,   107,   107,   nil,   nil,   103,   103,   106,   nil,
   nil,   107,   nil,   nil,   108,   108,   108,   nil,   nil,   104,
   104,   107,   105,   105,   108,   nil,   nil,   118,   118,   118,
   145,   145,   145,   nil,   108,   106,   106,   118,   nil,   nil,
   145,   nil,   nil,   162,   162,   162,   nil,   118,   107,   107,
   145,   nil,   nil,   162,   nil,   nil,   176,   176,   176,   nil,
   nil,   108,   108,   162,   nil,    14,   176,   133,   133,   133,
   133,   133,   nil,   nil,   118,   118,   176,   145,   145,   134,
   134,   134,   134,   134,   nil,   nil,   nil,    23,    14,   nil,
   162,   162,    14,    14,    14,   nil,    14,    14,    14,    14,
   nil,   nil,    14,   176,   176,   nil,    14,   nil,    14,    23,
    23,    86,   nil,   nil,    23,    23,    23,   nil,    23,    23,
    23,    23,   nil,   nil,    23,   nil,   nil,   nil,    23,   nil,
    23,   nil,    90,   nil,    86,   nil,   nil,   nil,    86,    86,
    86,   nil,    86,    86,    86,    86,   nil,   nil,    86,   117,
   nil,   nil,    86,   nil,    86,    90,   nil,   nil,   nil,    90,
    90,    90,   nil,    90,    90,    90,    90,   nil,   119,    90,
   nil,   nil,   117,    90,   nil,    90,   117,   117,   117,   nil,
   117,   117,   117,   117,   nil,   120,   117,   nil,   nil,   nil,
   117,   119,   117,   nil,   nil,   119,   119,   119,   nil,   119,
   119,   119,   119,   nil,   nil,   119,   nil,   121,   120,   119,
   nil,   119,   120,   120,   120,   nil,   120,   120,   120,   120,
   nil,   nil,   120,   nil,   123,   nil,   120,   nil,   120,   121,
   121,   nil,   nil,   nil,   121,   121,   121,   nil,   121,   121,
   121,   121,   nil,   nil,   121,   nil,   126,   123,   121,   nil,
   121,   123,   123,   123,   nil,   123,   123,   123,   123,   nil,
   nil,   123,   nil,   148,   nil,   123,   nil,   123,   126,   126,
   nil,   nil,   nil,   126,   126,   126,   nil,   126,   126,   126,
   126,   nil,   nil,   126,   nil,   148,   148,   126,   150,   126,
   148,   148,   148,   nil,   148,   148,   148,   148,   nil,   148,
   148,   nil,   nil,   nil,   148,   151,   148,   nil,   nil,   nil,
   150,   150,   nil,   nil,   nil,   150,   150,   150,   nil,   150,
   150,   150,   150,   nil,   153,   150,   nil,   151,   151,   150,
   nil,   150,   151,   151,   151,   nil,   151,   151,   151,   151,
   nil,   154,   151,   nil,   nil,   nil,   151,   153,   151,   nil,
   nil,   153,   153,   153,   nil,   153,   153,   153,   153,   nil,
   161,   153,   nil,   154,   154,   153,   nil,   153,   154,   154,
   154,   nil,   154,   154,   154,   154,   nil,   166,   154,   nil,
   nil,   nil,   154,   161,   154,   nil,   nil,   161,   161,   161,
   nil,   161,   161,   161,   161,   nil,   168,   161,   nil,   166,
   166,   161,   nil,   161,   166,   166,   166,   nil,   166,   166,
   166,   166,   nil,   170,   166,   nil,   nil,   nil,   166,   168,
   166,   nil,   nil,   168,   168,   168,   nil,   168,   168,   168,
   168,   nil,   nil,   168,   nil,   170,   170,   168,   174,   168,
   170,   170,   170,   nil,   170,   170,   170,   170,   nil,   nil,
   170,   nil,   nil,   nil,   170,   177,   170,   nil,   nil,   nil,
   174,   174,   nil,   nil,   nil,   174,   174,   174,   nil,   174,
   174,   174,   174,   nil,   nil,   174,   nil,   181,   177,   174,
   nil,   174,   177,   177,   177,   nil,   177,   177,   177,   177,
   nil,   nil,   177,   nil,   183,   nil,   177,   nil,   177,   181,
   181,   nil,   nil,   nil,   181,   181,   181,   nil,   181,   181,
   181,   181,   nil,   nil,   181,   nil,   185,   183,   181,   nil,
   181,   183,   183,   183,   nil,   183,   183,   183,   183,   nil,
   nil,   183,   nil,   nil,   nil,   183,   nil,   183,   185,   185,
   nil,   nil,   nil,   185,   185,   185,   nil,   185,   185,   185,
   185,   nil,   nil,   185,   nil,   nil,   nil,   185,   nil,   185,
    84,    84,    84,    84,    84,    84,    84,    84,    84,    84,
    84,    84,    84,    84,    84,   171,   171,   171,   171,   171,
   171,   171,   171,   171,   171,   171,   171,   171,   171,   171,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    84,
   171,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   171,   149,   149,   149,   149,   149,   149,   149,
   149,   149,   149,   149,   149,   149,   149,   149,    82,    82,
    82,    82,    82,    82,    82,    82,    82,    82,    82,    82,
    82,    82,    82,   nil,   nil,   nil,   nil,   nil,   nil,   149,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    82,    85,    85,    85,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    85,    85,    85,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    85,   180,   180,   180,
   180,   180,   180,   180,   180,   180,   180,   180,   180,   180,
   180,   180,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   180,   109,   109,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   nil,   nil,
   109,    62,    62,    62,    62,    62,    62,    62,    62,    62,
    62,    62,    62,    62,    62,    62,    78,    78,    78,    78,
    78,    78,    78,    78,    78,    78,    78,    78,    78,    78,
    78,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   112,   112,   112,   112,   112,   112,   113,   113,   113,   113,
   113,   113,   113,   113,   113,   113,   113,   113,   113,   113,
   113,   146,   146,   146,   146,   146,   146,   146,   146,   146,
   146,   146,   146,   146,   146,   146,   158,   158,   158,   158,
   158,   158,   158,   158,   158,   158,   158,   158,   158,   158,
   158,   142,   142,   142,   142,   142,   142,   142,   142,   142,
   142,   142,   142,   142,   142,   135,   135,   135,   135,   135,
   135,   135,   135,   135,   135,   135,   135,   135,   136,   136,
   136,   136,   136,   136,   136,   136,   136,   136,   136,   136,
   136,   137,   137,   137,   137,   137,   137,   137,   137,   137,
   137,   137,   137,   137,   138,   138,   138,   138,   138,   138,
   138,   138,   138,   138,   138,   138,   138,   139,   139,   139,
   139,   139,   139,   139,   139,   139,   139,   139,   139,   139,
   140,   140,   140,   140,   140,   140,   140,   140,   140,   140,
   140,   140,   140,   141,   141,   141,   141,   141,   141,   141,
   141,   141,   141,   141,   141,   141 ]

racc_action_pointer = [
    25,     8,   -20,   nil,     4,    46,    14,    86,   nil,   nil,
    76,   nil,    74,    30,   321,   nil,    14,    74,    75,   nil,
   101,   nil,   nil,   343,   nil,    80,    81,    85,    86,   101,
   104,   106,   nil,   107,   nil,     9,   -14,   132,    -2,     2,
    31,   133,    38,    53,     3,   117,   142,   nil,    -9,   118,
   nil,   115,   123,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   984,   nil,   nil,   131,    64,    67,    70,   nil,
   nil,   nil,   nil,   nil,    93,   106,   nil,   126,   999,   nil,
   nil,   130,   881,   118,   813,   914,   367,    36,     5,   133,
   388,   nil,   159,   nil,   119,   122,   135,   148,   161,   174,
   177,   190,   203,   216,   229,   232,   245,   258,   271,   966,
   nil,   nil,  1014,  1029,   nil,     0,    14,   405,   284,   424,
   441,   463,   142,   480,    43,    46,   502,   nil,   nil,   nil,
   nil,   nil,   nil,   320,   332,  1088,  1101,  1114,  1127,  1140,
  1153,  1166,  1074,   nil,   nil,   287,  1044,   nil,   519,   866,
   544,   561,   141,   580,   597,   150,   nil,   149,  1059,   nil,
   nil,   616,   300,   nil,   nil,   nil,   633,   156,   652,   nil,
   669,   828,   161,   nil,   694,   nil,   313,   711,   nil,   162,
   940,   733,   nil,   750,   nil,   772,   nil ]

racc_action_default = [
   -82,   -82,   -82,    -2,    -4,   -82,   -82,   -82,    -1,    -3,
   -82,   -81,   -82,   -82,   -82,   187,   -82,   -82,   -82,   -14,
   -82,   -74,   -75,   -82,   -21,   -82,   -82,   -82,   -82,   -82,
   -82,   -82,   -29,   -82,   -31,   -82,   -82,   -82,   -82,   -82,
   -82,   -82,   -82,   -82,   -82,   -82,   -82,   -11,   -82,   -16,
   -17,   -18,   -82,   -20,   -22,   -23,   -24,   -25,   -26,   -27,
   -28,   -30,   -32,   -49,   -50,   -51,   -82,   -82,   -82,   -76,
   -77,   -78,   -79,   -80,   -82,   -82,   -34,   -35,   -37,   -38,
   -41,   -36,   -82,   -82,   -82,   -82,   -82,   -82,   -82,   -10,
   -82,   -15,   -82,   -13,   -82,   -82,   -82,   -82,   -82,   -82,
   -82,   -82,   -82,   -82,   -82,   -82,   -82,   -82,   -82,   -82,
   -53,   -54,   -33,   -72,   -70,   -82,   -82,   -82,   -82,   -82,
   -82,   -82,   -82,   -82,   -82,   -82,   -82,   -19,   -55,   -56,
   -57,   -58,   -59,   -60,   -61,   -62,   -63,   -64,   -65,   -66,
   -67,   -68,   -69,   -52,   -71,   -82,   -39,   -40,   -82,   -82,
   -82,   -82,   -82,   -82,   -82,   -82,    -9,   -82,   -73,   -42,
   -43,   -82,   -82,   -47,   -48,    -5,   -82,   -82,   -82,   -12,
   -82,   -82,   -82,    -6,   -82,   -44,   -82,   -82,    -7,   -82,
   -82,   -82,    -8,   -82,   -46,   -82,   -45 ]

racc_goto_table = [
    10,    45,    19,     2,     3,     1,     8,     9,    12,    36,
    77,    81,    18,    49,    50,    51,   147,   159,    36,    46,
    23,   115,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    76,   nil,   nil,   nil,    83,    91,   nil,   nil,
   nil,    89,   nil,   nil,   nil,   nil,   nil,   nil,    33,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    33,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    36,   nil,   nil,   nil,    36,   nil,   127,   nil,   nil,
   122,   nil,   121,    53,   nil,   nil,   126,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   156,   nil,    36,   nil,    36,    36,    36,   nil,    36,   nil,
    33,    36,   nil,   148,    33,   150,   151,   155,    46,   154,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    36,   nil,    36,    36,   nil,    36,    36,
   nil,    33,   nil,    33,    33,    33,    36,    33,   nil,   166,
    33,    36,   nil,    36,   nil,    36,   nil,   170,   nil,    36,
   nil,   nil,    36,   nil,   174,   nil,    36,   nil,    36,   nil,
    36,   nil,    33,   181,    33,    33,   nil,    33,    33,   185,
   nil,    53,   nil,   nil,   nil,    33,    53,   nil,    62,   nil,
    33,   nil,    33,    82,    33,    84,    85,   nil,    33,   nil,
   nil,    33,   nil,   nil,   nil,    33,   nil,    33,    53,    33,
    53,    53,   nil,   nil,    53,   nil,   nil,   nil,   nil,   109,
   110,   111,   nil,   nil,   nil,   nil,    53,   112,   113,   nil,
    53,   nil,   nil,   nil,    53,   nil,   nil,   nil,   nil,   nil,
   nil,    53,   nil,   nil,   nil,    53,   nil,   128,   129,   130,
   131,   132,   133,   134,   135,   136,   137,   138,   139,   140,
   141,   142,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   146,
   nil,   149,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   158,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   171,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   180 ]

racc_goto_check = [
     5,     7,    11,     2,     3,     1,     3,     2,     9,     5,
    23,    23,    10,    12,    13,     5,    24,    25,     5,     8,
     6,    27,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     5,   nil,   nil,   nil,     5,    11,   nil,   nil,
   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     5,   nil,   nil,   nil,     5,   nil,     5,   nil,   nil,
     8,   nil,     6,    14,   nil,   nil,     6,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     7,   nil,     5,   nil,     5,     5,     5,   nil,     5,   nil,
    21,     5,   nil,     6,    21,     6,     6,     8,     8,     6,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5,   nil,     5,     5,   nil,     5,     5,
   nil,    21,   nil,    21,    21,    21,     5,    21,   nil,     6,
    21,     5,   nil,     5,   nil,     5,   nil,     6,   nil,     5,
   nil,   nil,     5,   nil,     6,   nil,     5,   nil,     5,   nil,
     5,   nil,    21,     6,    21,    21,   nil,    21,    21,     6,
   nil,    14,   nil,   nil,   nil,    21,    14,   nil,    22,   nil,
    21,   nil,    21,    22,    21,    22,    22,   nil,    21,   nil,
   nil,    21,   nil,   nil,   nil,    21,   nil,    21,    14,    21,
    14,    14,   nil,   nil,    14,   nil,   nil,   nil,   nil,    22,
    22,    22,   nil,   nil,   nil,   nil,    14,    22,    22,   nil,
    14,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,   nil,
   nil,    14,   nil,   nil,   nil,    14,   nil,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    22,    22,    22,    22,
    22,    22,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,
   nil,    22,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    22,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22 ]

racc_goto_pointer = [
   nil,     5,     3,     4,   nil,    -5,     6,   -15,     3,     2,
    -1,   -11,    -7,    -6,    70,   nil,   nil,   nil,   nil,   nil,
   nil,    34,   163,   -28,  -100,  -131,   nil,   -54,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,    65,   nil,   nil,    20,    32,
   nil,   nil,   nil,    25,    24,    26,    27,    28,    29,    30,
    31,    64,    78,   nil,    79,   nil,    63,   nil,    69,    70 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 53, :_reduce_1,
  1, 53, :_reduce_2,
  2, 54, :_reduce_3,
  1, 54, :_reduce_4,
  8, 56, :_reduce_5,
  9, 56, :_reduce_6,
  10, 56, :_reduce_7,
  11, 56, :_reduce_8,
  4, 59, :_reduce_9,
  2, 59, :_reduce_10,
  4, 55, :_reduce_11,
  7, 61, :_reduce_12,
  4, 61, :_reduce_13,
  1, 62, :_reduce_14,
  3, 62, :_reduce_15,
  2, 63, :_reduce_16,
  2, 63, :_reduce_17,
  1, 64, :_reduce_18,
  3, 64, :_reduce_19,
  2, 58, :_reduce_20,
  1, 58, :_reduce_21,
  2, 66, :_reduce_22,
  2, 66, :_reduce_23,
  2, 66, :_reduce_24,
  2, 66, :_reduce_25,
  2, 66, :_reduce_26,
  2, 66, :_reduce_27,
  2, 66, :_reduce_28,
  1, 66, :_reduce_29,
  2, 66, :_reduce_30,
  1, 66, :_reduce_31,
  2, 72, :_reduce_32,
  3, 65, :_reduce_33,
  2, 67, :_reduce_34,
  2, 68, :_reduce_35,
  2, 68, :_reduce_36,
  1, 75, :_reduce_37,
  1, 75, :_reduce_38,
  3, 75, :_reduce_39,
  3, 75, :_reduce_40,
  1, 76, :_reduce_41,
  5, 69, :_reduce_42,
  1, 77, :_reduce_43,
  3, 77, :_reduce_44,
  11, 70, :_reduce_45,
  9, 70, :_reduce_46,
  5, 70, :_reduce_47,
  5, 71, :_reduce_48,
  1, 74, :_reduce_49,
  1, 74, :_reduce_50,
  1, 74, :_reduce_51,
  3, 74, :_reduce_52,
  2, 74, :_reduce_53,
  2, 74, :_reduce_54,
  3, 74, :_reduce_55,
  3, 74, :_reduce_56,
  3, 74, :_reduce_57,
  3, 74, :_reduce_58,
  3, 74, :_reduce_59,
  3, 74, :_reduce_60,
  3, 74, :_reduce_61,
  3, 74, :_reduce_62,
  3, 74, :_reduce_63,
  3, 74, :_reduce_64,
  3, 74, :_reduce_65,
  3, 74, :_reduce_66,
  3, 74, :_reduce_67,
  3, 74, :_reduce_68,
  3, 74, :_reduce_69,
  3, 73, :_reduce_70,
  4, 73, :_reduce_71,
  1, 79, :_reduce_72,
  3, 79, :_reduce_73,
  1, 60, :_reduce_74,
  1, 60, :_reduce_75,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 80, :_reduce_78,
  1, 81, :_reduce_79,
  1, 81, :_reduce_80,
  1, 57, :_reduce_81 ]

racc_reduce_n = 82

racc_shift_n = 187

racc_token_table = {
  false => 0,
  :error => 1,
  "TkString" => 2,
  "TkNum" => 3,
  "TkId" => 4,
  "not" => 5,
  :UMINUS => 6,
  "*" => 7,
  "/" => 8,
  "%" => 9,
  "div" => 10,
  "mod" => 11,
  "+" => 12,
  "-" => 13,
  "==" => 14,
  "/=" => 15,
  ">=" => 16,
  "<=" => 17,
  ">" => 18,
  "<" => 19,
  "and" => 20,
  "or" => 21,
  "func" => 22,
  "(" => 23,
  ")" => 24,
  "begin" => 25,
  "end" => 26,
  ";" => 27,
  "->" => 28,
  "," => 29,
  "program" => 30,
  "with" => 31,
  "do" => 32,
  "return" => 33,
  "=" => 34,
  "read" => 35,
  "write" => 36,
  "writeln" => 37,
  "if" => 38,
  "then" => 39,
  "else" => 40,
  "for" => 41,
  "from" => 42,
  "to" => 43,
  "by" => 44,
  "repeat" => 45,
  "times" => 46,
  "while" => 47,
  "number" => 48,
  "boolean" => 49,
  "true" => 50,
  "false" => 51 }

racc_nt_base = 52

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"TkString\"",
  "\"TkNum\"",
  "\"TkId\"",
  "\"not\"",
  "UMINUS",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"div\"",
  "\"mod\"",
  "\"+\"",
  "\"-\"",
  "\"==\"",
  "\"/=\"",
  "\">=\"",
  "\"<=\"",
  "\">\"",
  "\"<\"",
  "\"and\"",
  "\"or\"",
  "\"func\"",
  "\"(\"",
  "\")\"",
  "\"begin\"",
  "\"end\"",
  "\";\"",
  "\"->\"",
  "\",\"",
  "\"program\"",
  "\"with\"",
  "\"do\"",
  "\"return\"",
  "\"=\"",
  "\"read\"",
  "\"write\"",
  "\"writeln\"",
  "\"if\"",
  "\"then\"",
  "\"else\"",
  "\"for\"",
  "\"from\"",
  "\"to\"",
  "\"by\"",
  "\"repeat\"",
  "\"times\"",
  "\"while\"",
  "\"number\"",
  "\"boolean\"",
  "\"true\"",
  "\"false\"",
  "$start",
  "ESTRUCTURA",
  "FUNCIONES",
  "PROGRAMA",
  "FUNCION",
  "IDENTIFICADOR",
  "INSTRUCCIONES",
  "PARAMETROS",
  "TIPO",
  "BLOQUE",
  "LISTA_DECLARACION",
  "DECLARACION",
  "LISTA_IDENTIFICADOR",
  "ASIGNACION",
  "INSTRUCCION",
  "ENTRADA",
  "SALIDA",
  "CONDICIONAL",
  "REPETICION_D",
  "REPETICION_I",
  "RETURN",
  "LLAMADA_FUNCION",
  "EXPRESION",
  "ESCRIBIR",
  "STRING",
  "COND",
  "LITERAL",
  "LISTA_PASE_PARAMETROS",
  "LITERAL_NUMBER",
  "LITERAL_BOOLEAN" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_1(val, _values, result)
     return Estructura.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_2(val, _values, result)
     return Estructura.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_3(val, _values, result)
     result = ListaFunciones.new(val[1], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_4(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_5(val, _values, result)
     result = Funcion.new(val[1], nil, nil, val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_6(val, _values, result)
     result = Funcion.new(val[1], val[3], nil, val[6]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_7(val, _values, result)
     result = Funcion.new(val[1], nil, val[5], val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_8(val, _values, result)
     result = Funcion.new(val[1], val[3], val[6], val[8]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_9(val, _values, result)
     result = Parametros.new(val[0],val[1],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_10(val, _values, result)
     result = Parametros.new(val[0],val[1],nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_11(val, _values, result)
     result = Programa.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_12(val, _values, result)
     result = Bloque.new(val[1], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_13(val, _values, result)
     result = Bloque.new(nil, val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_14(val, _values, result)
     result = ListaDeclaracion.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_15(val, _values, result)
     result = ListaDeclaracion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_16(val, _values, result)
     result = Declaracion.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_17(val, _values, result)
     result = Declaracion.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_18(val, _values, result)
     result = ListaId.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_19(val, _values, result)
     result = ListaId.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_20(val, _values, result)
     result = Instrucciones.new(val[1], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_21(val, _values, result)
     result = Instrucciones.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_22(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 97)
  def _reduce_23(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_24(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_25(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_26(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 101)
  def _reduce_27(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 102)
  def _reduce_28(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 103)
  def _reduce_29(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 104)
  def _reduce_30(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 105)
  def _reduce_31(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 110)
  def _reduce_32(val, _values, result)
     result = Return.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_33(val, _values, result)
     result = Asignacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_34(val, _values, result)
     result = Entrada.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_35(val, _values, result)
     result = Salida.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 126)
  def _reduce_36(val, _values, result)
     result = Salida.new(val[1], "SALTO") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 131)
  def _reduce_37(val, _values, result)
     result = Escribir.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 132)
  def _reduce_38(val, _values, result)
     result = Escribir.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_39(val, _values, result)
     result = Escribir.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_40(val, _values, result)
     result = Escribir.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 138)
  def _reduce_41(val, _values, result)
     result = Str.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_42(val, _values, result)
     result = Condicional.new(val[1],val[3],val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 147)
  def _reduce_43(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 148)
  def _reduce_44(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 153)
  def _reduce_45(val, _values, result)
     result = For.new(val[1], val[3], val[5], val[7], val[9])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 154)
  def _reduce_46(val, _values, result)
     result = For.new(val[1], val[3], val[5], nil, val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_47(val, _values, result)
     result = Repeat.new(val[1],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_48(val, _values, result)
     result = RepeticionI.new(val[1],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_49(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 166)
  def _reduce_50(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_51(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 168)
  def _reduce_52(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 169)
  def _reduce_53(val, _values, result)
     result = OpNot.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 170)
  def _reduce_54(val, _values, result)
     result = OpUMINUS.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 171)
  def _reduce_55(val, _values, result)
     result = OpMultiplicacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_56(val, _values, result)
     result = OpDivisionE.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 173)
  def _reduce_57(val, _values, result)
     result = OpModE.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 174)
  def _reduce_58(val, _values, result)
     result = OpDivision.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 175)
  def _reduce_59(val, _values, result)
     result = OpMod.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 176)
  def _reduce_60(val, _values, result)
     result = OpSuma.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 177)
  def _reduce_61(val, _values, result)
     result = OpResta.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 178)
  def _reduce_62(val, _values, result)
     result = OpEquivalente.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 179)
  def _reduce_63(val, _values, result)
     result = OpDesigual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 180)
  def _reduce_64(val, _values, result)
     result = OpMayorIgual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 181)
  def _reduce_65(val, _values, result)
     result = OpMenorIgual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 182)
  def _reduce_66(val, _values, result)
     result = OpMayor.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 183)
  def _reduce_67(val, _values, result)
     result = OpMenor.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 184)
  def _reduce_68(val, _values, result)
     result = OpAnd.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 185)
  def _reduce_69(val, _values, result)
     result = OpOr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 190)
  def _reduce_70(val, _values, result)
     result = LlamadaFuncion.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 191)
  def _reduce_71(val, _values, result)
     result = LlamadaFuncion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 195)
  def _reduce_72(val, _values, result)
     result = ListaPaseParametros.new(nil,val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 196)
  def _reduce_73(val, _values, result)
     result = ListaPaseParametros.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 201)
  def _reduce_74(val, _values, result)
     result = TipoNum.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 202)
  def _reduce_75(val, _values, result)
     result = TipoBoolean.new() 
    result
  end
.,.,

# reduce 76 omitted

# reduce 77 omitted

module_eval(<<'.,.,', 'parser.y', 213)
  def _reduce_78(val, _values, result)
     result = LiteralNumerico.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_79(val, _values, result)
     result = LiteralBooleano.new("true") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 219)
  def _reduce_80(val, _values, result)
     result = LiteralBooleano.new("false") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_81(val, _values, result)
     result =  Identificador.new(val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserRtn
