#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
class ParserRtn < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 193)

load 'MainRtn.rb'
load 'clasesParser.rb'
	
	def initialize(tokens)
		@tokens = tokens
		@yydebug = true
	end 

	def parse
		do_parse
	end

	def next_token
		@tokens.next_token
	end

	
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    61,    34,    35,    36,    12,    13,    37,     6,     7,    40,
    38,    18,    19,     6,    39,    52,    99,   148,    12,    13,
     5,    49,    50,    44,    10,   149,    18,    19,   134,    34,
    35,    36,    12,    13,    37,    14,    15,    40,    38,    20,
    53,   100,    39,    43,    54,    51,    55,    48,    45,    49,
    50,    44,    56,     5,    18,    19,   151,    34,    35,    36,
    12,    13,    37,   103,   104,    40,    38,   105,   -19,    57,
    39,    43,    63,    51,    64,    48,    45,    49,    50,    44,
    18,    19,    18,    19,   152,    34,    35,    36,    12,    13,
    37,    65,    66,    40,    38,    67,    68,    85,    39,    43,
    91,    51,   101,    48,    45,    49,    50,    44,   106,   123,
   123,   125,   167,    34,    35,    36,    12,    13,    37,   129,
   130,    40,    38,    51,   142,   144,    39,    43,   145,    51,
   146,    48,    45,    49,    50,    44,   153,   154,   158,   159,
   169,    34,    35,    36,    12,    13,    37,   160,   163,    40,
    38,   nil,   nil,   nil,    39,    43,   nil,    51,   nil,    48,
    45,    49,    50,    44,    70,    71,    72,    73,    74,    34,
    35,    36,    12,    13,    37,   nil,   nil,    40,    38,   nil,
   nil,   nil,    39,    43,   nil,    51,   nil,    48,    45,    49,
    50,    44,    70,    71,    72,    73,    74,    34,    35,    36,
    12,    13,    37,   nil,   nil,    40,    38,   nil,   nil,   nil,
    39,    43,   nil,    51,   nil,    48,    45,    49,    50,    44,
   nil,   nil,   nil,   nil,   nil,    34,    35,    36,    12,    13,
    37,   nil,   nil,    40,    38,   nil,   nil,   nil,    39,    43,
   nil,    51,   nil,    48,    45,    49,    50,    44,   nil,   nil,
   nil,   nil,   nil,    34,    35,    36,    12,    13,    37,   nil,
   nil,    40,    38,   nil,   nil,   nil,    39,    43,   nil,    51,
   nil,    48,    45,    49,    50,    44,   nil,   nil,   nil,   nil,
   nil,    34,    35,    36,    12,    13,    37,   nil,   nil,    40,
    38,   nil,   nil,   nil,    39,    43,   nil,    51,   nil,    48,
    45,    49,    50,    44,   nil,   nil,   nil,   nil,   nil,    34,
    35,    36,    12,    13,    37,   nil,   nil,    40,    38,   nil,
   nil,   nil,    39,    43,   nil,    51,   nil,    48,    45,    49,
    50,    44,   nil,   nil,   nil,   nil,   nil,    34,    35,    36,
    12,    13,    37,   nil,   nil,    40,    38,   nil,   nil,   nil,
    39,    43,   nil,    51,   nil,    48,    45,    49,    50,    44,
   nil,   nil,   nil,   nil,   nil,    34,    35,    36,    12,    13,
    37,   nil,   nil,    40,    38,   nil,   nil,   nil,    39,    43,
   nil,    51,   nil,    48,    45,    49,    50,    44,   nil,   nil,
   nil,   nil,   nil,    34,    35,    36,    12,    13,    37,   nil,
   nil,    40,    38,   nil,   nil,   nil,    39,    43,   nil,    51,
   nil,    48,    45,    49,    50,    44,   nil,   nil,   nil,   nil,
   nil,    34,    35,    36,    12,    13,    37,   nil,   nil,    40,
    38,   nil,   nil,   nil,    39,    43,   nil,    51,   nil,    48,
    45,    49,    50,    44,   nil,   nil,   nil,   nil,   nil,    34,
    35,    36,    12,    13,    37,   nil,   nil,    40,    38,   nil,
   nil,   nil,    39,    43,   nil,    51,   nil,    48,    45,    49,
    50,    44,   nil,   nil,   nil,   nil,   nil,    34,    35,    36,
    12,    13,    37,   127,   nil,    40,    38,   nil,   nil,   nil,
    39,    43,   nil,    51,   nil,    48,    45,    49,    50,    44,
   nil,   nil,    83,    84,    77,    78,    79,    80,    81,    82,
    75,    76,    70,    71,    72,    73,    74,   162,   nil,    43,
   nil,    51,   nil,    48,    45,   161,   nil,   nil,   nil,   nil,
   nil,   nil,   166,   nil,   nil,   nil,    83,    84,    77,    78,
    79,    80,    81,    82,    75,    76,    70,    71,    72,    73,
    74,    83,    84,    77,    78,    79,    80,    81,    82,    75,
    76,    70,    71,    72,    73,    74,   124,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    49,    50,    44,   nil,
   nil,   nil,   nil,    83,    84,    77,    78,    79,    80,    81,
    82,    75,    76,    70,    71,    72,    73,    74,    43,   nil,
    51,   nil,    48,    45,    49,    50,    44,   nil,   nil,   nil,
    49,    50,    44,   nil,   nil,   nil,    49,    50,    44,   nil,
   nil,   nil,    49,    50,    44,   nil,    43,   nil,    51,    88,
    48,    45,    43,   nil,    51,    88,    48,    45,    43,   nil,
    51,   nil,    48,    45,    43,   nil,    51,   nil,    48,    45,
    49,    50,    44,   nil,   nil,   nil,    49,    50,    44,   nil,
   nil,   nil,    49,    50,    44,   nil,   nil,   nil,    49,    50,
    44,   nil,    43,   nil,    51,   nil,    48,    45,    43,   nil,
    51,   nil,    48,    45,    43,   nil,    51,   nil,    48,    45,
    43,   nil,    51,   nil,    48,    45,    49,    50,    44,   nil,
   nil,   nil,    49,    50,    44,   nil,   nil,   nil,    49,    50,
    44,   nil,   nil,   nil,    49,    50,    44,   nil,    43,   nil,
    51,   nil,    48,    45,    43,   nil,    51,   nil,    48,    45,
    43,   nil,    51,   nil,    48,    45,    43,   nil,    51,   nil,
    48,    45,    49,    50,    44,   nil,   nil,   nil,    49,    50,
    44,   nil,   nil,   nil,    49,    50,    44,   nil,   nil,   nil,
    49,    50,    44,   nil,    43,   nil,    51,   nil,    48,    45,
    43,   nil,    51,   nil,    48,    45,    43,   nil,    51,   nil,
    48,    45,    43,   nil,    51,   nil,    48,    45,    49,    50,
    44,   nil,   nil,   nil,    49,    50,    44,   nil,   nil,   nil,
    49,    50,    44,   nil,   nil,   nil,    49,    50,    44,   nil,
    43,   nil,    51,   nil,    48,    45,    43,   nil,    51,   nil,
    48,    45,    43,   nil,    51,   nil,    48,    45,    43,   nil,
    51,   nil,    48,    45,    49,    50,    44,   nil,   nil,   nil,
    49,    50,    44,   nil,   nil,   nil,    49,    50,    44,   nil,
   nil,   nil,    49,    50,    44,   nil,    43,   nil,    51,   nil,
    48,    45,    43,   nil,    51,   nil,    48,    45,    43,   nil,
    51,   nil,    48,    45,    43,   nil,    51,   nil,    48,    45,
    49,    50,    44,   nil,   nil,   nil,    49,    50,    44,   nil,
   nil,   nil,    49,    50,    44,   nil,   nil,   nil,    49,    50,
    44,   nil,    43,   nil,    51,   137,    48,    45,    43,   nil,
    51,   nil,    48,    45,    43,   150,    51,   nil,    48,    45,
    43,   nil,    51,   nil,    48,    45,   nil,    83,    84,    77,
    78,    79,    80,    81,    82,    75,    76,    70,    71,    72,
    73,    74,   126,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    83,    84,    77,    78,    79,    80,    81,    82,    75,
    76,    70,    71,    72,    73,    74,    83,    84,    77,    78,
    79,    80,    81,    82,    75,    76,    70,    71,    72,    73,
    74,   nil,   nil,   nil,   nil,   nil,   128,    83,    84,    77,
    78,    79,    80,    81,    82,    75,    76,    70,    71,    72,
    73,    74,    69,    83,    84,    77,    78,    79,    80,    81,
    82,    75,    76,    70,    71,    72,    73,    74,    83,    84,
    77,    78,    79,    80,    81,    82,    75,    76,    70,    71,
    72,    73,    74,    83,   nil,    77,    78,    79,    80,    81,
    82,    75,    76,    70,    71,    72,    73,    74,    83,    84,
    77,    78,    79,    80,    81,    82,    75,    76,    70,    71,
    72,    73,    74,   -74,   -74,   -74,   -74,   -74,   -74,    75,
    76,    70,    71,    72,    73,    74,   -74,   -74,   -74,   -74,
   -74,   -74,    75,    76,    70,    71,    72,    73,    74,   -74,
   -74,   -74,   -74,   -74,   -74,    75,    76,    70,    71,    72,
    73,    74,   -74,   -74,   -74,   -74,   -74,   -74,    75,    76,
    70,    71,    72,    73,    74,   -74,   -74,   -74,   -74,   -74,
   -74,    75,    76,    70,    71,    72,    73,    74,   -74,   -74,
   -74,   -74,   -74,   -74,    75,    76,    70,    71,    72,    73,
    74,    77,    78,    79,    80,    81,    82,    75,    76,    70,
    71,    72,    73,    74 ]

racc_action_check = [
    23,    23,    23,    23,    23,    23,    23,     0,     1,    23,
    23,    10,    10,     2,    23,    15,    54,   138,     6,     6,
     4,    23,    23,    23,     5,   138,    12,    12,   102,   102,
   102,   102,   102,   102,   102,     7,    10,   102,   102,    11,
    15,    54,   102,    23,    16,    23,    17,    23,    23,   102,
   102,   102,    20,     0,    53,    53,   140,   140,   140,   140,
   140,   140,   140,    58,    58,   140,   140,    59,    59,    21,
   140,   102,    26,   102,    27,   102,   102,   140,   140,   140,
   100,   100,   101,   101,   141,   141,   141,   141,   141,   141,
   141,    28,    29,   141,   141,    30,    31,    34,   141,   140,
    38,   140,    55,   140,   140,   141,   141,   141,    61,    86,
    89,    91,   165,   165,   165,   165,   165,   165,   165,    97,
    98,   165,   165,   104,   129,   131,   165,   141,   132,   141,
   134,   141,   141,   165,   165,   165,   143,   144,   153,   155,
   168,   168,   168,   168,   168,   168,   168,   156,   159,   168,
   168,   nil,   nil,   nil,   168,   165,   nil,   165,   nil,   165,
   165,   168,   168,   168,   113,   113,   113,   113,   113,    13,
    13,    13,    13,    13,    13,   nil,   nil,    13,    13,   nil,
   nil,   nil,    13,   168,   nil,   168,   nil,   168,   168,    13,
    13,    13,   114,   114,   114,   114,   114,    52,    52,    52,
    52,    52,    52,   nil,   nil,    52,    52,   nil,   nil,   nil,
    52,    13,   nil,    13,   nil,    13,    13,    52,    52,    52,
   nil,   nil,   nil,   nil,   nil,    57,    57,    57,    57,    57,
    57,   nil,   nil,    57,    57,   nil,   nil,   nil,    57,    52,
   nil,    52,   nil,    52,    52,    57,    57,    57,   nil,   nil,
   nil,   nil,   nil,    99,    99,    99,    99,    99,    99,   nil,
   nil,    99,    99,   nil,   nil,   nil,    99,    57,   nil,    57,
   nil,    57,    57,    99,    99,    99,   nil,   nil,   nil,   nil,
   nil,   124,   124,   124,   124,   124,   124,   nil,   nil,   124,
   124,   nil,   nil,   nil,   124,    99,   nil,    99,   nil,    99,
    99,   124,   124,   124,   nil,   nil,   nil,   nil,   nil,   126,
   126,   126,   126,   126,   126,   nil,   nil,   126,   126,   nil,
   nil,   nil,   126,   124,   nil,   124,   nil,   124,   124,   126,
   126,   126,   nil,   nil,   nil,   nil,   nil,   127,   127,   127,
   127,   127,   127,   nil,   nil,   127,   127,   nil,   nil,   nil,
   127,   126,   nil,   126,   nil,   126,   126,   127,   127,   127,
   nil,   nil,   nil,   nil,   nil,   130,   130,   130,   130,   130,
   130,   nil,   nil,   130,   130,   nil,   nil,   nil,   130,   127,
   nil,   127,   nil,   127,   127,   130,   130,   130,   nil,   nil,
   nil,   nil,   nil,   145,   145,   145,   145,   145,   145,   nil,
   nil,   145,   145,   nil,   nil,   nil,   145,   130,   nil,   130,
   nil,   130,   130,   145,   145,   145,   nil,   nil,   nil,   nil,
   nil,   149,   149,   149,   149,   149,   149,   nil,   nil,   149,
   149,   nil,   nil,   nil,   149,   145,   nil,   145,   nil,   145,
   145,   149,   149,   149,   nil,   nil,   nil,   nil,   nil,   162,
   162,   162,   162,   162,   162,   nil,   nil,   162,   162,   nil,
   nil,   nil,   162,   149,   nil,   149,   nil,   149,   149,   162,
   162,   162,   nil,   nil,   nil,   nil,   nil,   166,   166,   166,
   166,   166,   166,    93,   nil,   166,   166,   nil,   nil,   nil,
   166,   162,   nil,   162,   nil,   162,   162,   166,   166,   166,
   nil,   nil,    93,    93,    93,    93,    93,    93,    93,    93,
    93,    93,    93,    93,    93,    93,    93,   157,   nil,   166,
   nil,   166,   nil,   166,   166,   157,   nil,   nil,   nil,   nil,
   nil,   nil,   164,   nil,   nil,   nil,   157,   157,   157,   157,
   157,   157,   157,   157,   157,   157,   157,   157,   157,   157,
   157,   164,   164,   164,   164,   164,   164,   164,   164,   164,
   164,   164,   164,   164,   164,   164,    90,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    22,    22,    22,   nil,
   nil,   nil,   nil,    90,    90,    90,    90,    90,    90,    90,
    90,    90,    90,    90,    90,    90,    90,    90,    22,   nil,
    22,   nil,    22,    22,    35,    35,    35,   nil,   nil,   nil,
    36,    36,    36,   nil,   nil,   nil,    37,    37,    37,   nil,
   nil,   nil,    39,    39,    39,   nil,    35,   nil,    35,    35,
    35,    35,    36,   nil,    36,    36,    36,    36,    37,   nil,
    37,   nil,    37,    37,    39,   nil,    39,   nil,    39,    39,
    40,    40,    40,   nil,   nil,   nil,    43,    43,    43,   nil,
   nil,   nil,    44,    44,    44,   nil,   nil,   nil,    45,    45,
    45,   nil,    40,   nil,    40,   nil,    40,    40,    43,   nil,
    43,   nil,    43,    43,    44,   nil,    44,   nil,    44,    44,
    45,   nil,    45,   nil,    45,    45,    69,    69,    69,   nil,
   nil,   nil,    70,    70,    70,   nil,   nil,   nil,    71,    71,
    71,   nil,   nil,   nil,    72,    72,    72,   nil,    69,   nil,
    69,   nil,    69,    69,    70,   nil,    70,   nil,    70,    70,
    71,   nil,    71,   nil,    71,    71,    72,   nil,    72,   nil,
    72,    72,    73,    73,    73,   nil,   nil,   nil,    74,    74,
    74,   nil,   nil,   nil,    75,    75,    75,   nil,   nil,   nil,
    76,    76,    76,   nil,    73,   nil,    73,   nil,    73,    73,
    74,   nil,    74,   nil,    74,    74,    75,   nil,    75,   nil,
    75,    75,    76,   nil,    76,   nil,    76,    76,    77,    77,
    77,   nil,   nil,   nil,    78,    78,    78,   nil,   nil,   nil,
    79,    79,    79,   nil,   nil,   nil,    80,    80,    80,   nil,
    77,   nil,    77,   nil,    77,    77,    78,   nil,    78,   nil,
    78,    78,    79,   nil,    79,   nil,    79,    79,    80,   nil,
    80,   nil,    80,    80,    81,    81,    81,   nil,   nil,   nil,
    82,    82,    82,   nil,   nil,   nil,    83,    83,    83,   nil,
   nil,   nil,    84,    84,    84,   nil,    81,   nil,    81,   nil,
    81,    81,    82,   nil,    82,   nil,    82,    82,    83,   nil,
    83,   nil,    83,    83,    84,   nil,    84,   nil,    84,    84,
   123,   123,   123,   nil,   nil,   nil,   125,   125,   125,   nil,
   nil,   nil,   150,   150,   150,   nil,   nil,   nil,   161,   161,
   161,   nil,   123,   nil,   123,   123,   123,   123,   125,   nil,
   125,   nil,   125,   125,   150,   139,   150,   nil,   150,   150,
   161,   nil,   161,   nil,   161,   161,   nil,   139,   139,   139,
   139,   139,   139,   139,   139,   139,   139,   139,   139,   139,
   139,   139,    92,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    92,    92,    92,    92,    92,    92,    92,    92,    92,
    92,    92,    92,    92,    92,    92,    94,    94,    94,    94,
    94,    94,    94,    94,    94,    94,    94,    94,    94,    94,
    94,   nil,   nil,   nil,   nil,   nil,    94,    33,    33,    33,
    33,    33,    33,    33,    33,    33,    33,    33,    33,    33,
    33,    33,    33,    87,    87,    87,    87,    87,    87,    87,
    87,    87,    87,    87,    87,    87,    87,    87,   107,   107,
   107,   107,   107,   107,   107,   107,   107,   107,   107,   107,
   107,   107,   107,   122,   nil,   122,   122,   122,   122,   122,
   122,   122,   122,   122,   122,   122,   122,   122,   136,   136,
   136,   136,   136,   136,   136,   136,   136,   136,   136,   136,
   136,   136,   136,   115,   115,   115,   115,   115,   115,   115,
   115,   115,   115,   115,   115,   115,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   116,   116,   117,
   117,   117,   117,   117,   117,   117,   117,   117,   117,   117,
   117,   117,   118,   118,   118,   118,   118,   118,   118,   118,
   118,   118,   118,   118,   118,   119,   119,   119,   119,   119,
   119,   119,   119,   119,   119,   119,   119,   119,   120,   120,
   120,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   121,   121,   121,   121,   121,   121,   121,   121,   121,
   121,   121,   121,   121 ]

racc_action_pointer = [
     5,     8,    11,   nil,   -28,   -22,    11,    35,   nil,   nil,
   -11,    36,     4,   165,   nil,    -5,    -3,    -2,   nil,   nil,
     9,    61,   552,    -3,   nil,   nil,    29,    31,    48,    49,
    52,    53,   nil,   960,    49,   580,   586,   592,    52,   598,
   626,   nil,   nil,   632,   638,   644,   nil,   nil,   nil,   nil,
   nil,   nil,   193,    32,    -4,    58,   nil,   221,    20,    24,
   nil,    65,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   672,
   678,   684,   690,   718,   724,   730,   736,   764,   770,   776,
   782,   810,   816,   822,   828,   nil,    65,   976,   nil,    66,
   556,    97,   924,   475,   939,   nil,   nil,   116,   100,   249,
    58,    60,    25,   nil,    75,   nil,   nil,   991,   nil,   nil,
   nil,   nil,   nil,   127,   155,  1034,  1047,  1060,  1073,  1086,
  1099,  1112,  1006,   856,   277,   862,   305,   333,   nil,    81,
   361,   122,   108,   nil,    87,   nil,  1021,   nil,    14,   900,
    53,    81,   nil,   133,    94,   389,   nil,   nil,   nil,   417,
   868,   nil,   nil,    95,   nil,   136,   144,   509,   nil,   105,
   nil,   874,   445,   nil,   524,   109,   473,   nil,   137,   nil ]

racc_action_default = [
   -74,   -74,   -74,    -2,    -4,   -74,   -74,   -74,    -1,    -3,
   -74,   -74,   -74,   -74,   170,   -74,   -74,   -74,   -66,   -67,
   -74,   -74,   -74,   -74,   -21,   -22,   -74,   -74,   -74,   -74,
   -74,   -74,   -30,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -74,   -46,   -47,   -74,   -74,   -74,   -68,   -69,   -70,   -71,
   -72,   -73,   -74,   -74,   -74,   -10,   -11,   -74,   -74,   -47,
   -18,   -74,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -74,
   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -74,   -74,   -74,   -74,   -74,   -32,   -33,   -35,   -36,   -34,
   -74,   -74,   -74,   -74,   -74,   -49,   -50,   -74,   -74,   -74,
   -74,   -74,   -74,   -16,   -74,   -17,   -13,   -31,   -51,   -52,
   -53,   -54,   -55,   -56,   -57,   -58,   -59,   -60,   -61,   -62,
   -63,   -64,   -65,   -74,   -74,   -74,   -74,   -74,   -48,   -74,
   -74,   -74,   -74,    -9,   -74,   -20,   -37,   -38,   -74,   -74,
   -74,   -74,    -5,   -74,   -74,   -74,   -12,   -39,   -40,   -74,
   -74,   -44,   -45,   -74,    -6,   -74,   -74,   -74,    -7,   -74,
   -41,   -74,   -74,    -8,   -74,   -74,   -74,   -43,   -74,   -42 ]

racc_goto_table = [
    23,    62,    16,    59,     2,     3,     1,     8,     9,    86,
    89,    87,    87,    90,    11,    92,    93,    21,    58,    94,
    95,    96,    22,    60,   147,   nil,   nil,   nil,   nil,   nil,
    97,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   102,   107,   108,   109,   110,   111,
   112,   113,   114,   115,   116,   117,   118,   119,   120,   121,
   122,   nil,   nil,    98,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   131,   nil,   nil,
    62,   nil,   nil,   nil,   nil,   135,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   133,   nil,   nil,   nil,   nil,   nil,   136,
   nil,   139,   138,   nil,   nil,   nil,   nil,   nil,   143,   nil,
   132,   nil,   nil,   140,   141,   nil,   nil,   nil,    62,    62,
   nil,   nil,   nil,   155,   nil,   nil,   157,   156,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   164,   nil,   nil,
   nil,   nil,   nil,    62,   nil,   nil,    62,   nil,   nil,   165,
   nil,   nil,   nil,   168 ]

racc_goto_check = [
    10,     5,     6,    13,     2,     3,     1,     3,     2,    22,
    22,    21,    21,    21,     8,    21,    21,     9,    12,    21,
    21,    21,     7,    14,    23,   nil,   nil,   nil,   nil,   nil,
     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    10,    21,    21,    21,    21,    21,
    21,    21,    21,    21,    21,    21,    21,    21,    21,    21,
    21,   nil,   nil,     7,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,
     5,   nil,   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil,    21,
   nil,    21,     5,   nil,   nil,   nil,   nil,   nil,     5,   nil,
     7,   nil,   nil,    10,    10,   nil,   nil,   nil,     5,     5,
   nil,   nil,   nil,     5,   nil,   nil,    21,     5,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,
   nil,   nil,   nil,     5,   nil,   nil,     5,   nil,   nil,    10,
   nil,   nil,   nil,    10 ]

racc_goto_pointer = [
   nil,     6,     4,     5,   nil,   -22,    -8,    10,     8,     5,
   -13,   nil,    -4,   -19,     1,   nil,   nil,   nil,   nil,   nil,
   nil,   -24,   -26,  -114,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,    25,   nil,    17,    32,   nil,
   nil,   nil,   nil,    42,    26,    24,    27,    28,    29,    30,
    31,    33,   nil,   nil,    41,    46,    47 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 53, :_reduce_none,
  1, 53, :_reduce_none,
  2, 54, :_reduce_none,
  1, 54, :_reduce_none,
  7, 56, :_reduce_none,
  8, 56, :_reduce_none,
  9, 56, :_reduce_none,
  10, 56, :_reduce_none,
  4, 58, :_reduce_none,
  2, 58, :_reduce_none,
  4, 55, :_reduce_none,
  6, 60, :_reduce_none,
  4, 60, :_reduce_none,
  3, 63, :_reduce_none,
  2, 63, :_reduce_none,
  3, 61, :_reduce_none,
  3, 61, :_reduce_none,
  2, 61, :_reduce_none,
  1, 64, :_reduce_none,
  3, 64, :_reduce_none,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  2, 67, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  1, 57, :_reduce_none,
  3, 66, :_reduce_none,
  2, 68, :_reduce_none,
  2, 69, :_reduce_none,
  2, 69, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  3, 74, :_reduce_none,
  3, 74, :_reduce_none,
  5, 70, :_reduce_none,
  1, 75, :_reduce_40,
  3, 75, :_reduce_41,
  11, 71, :_reduce_none,
  9, 71, :_reduce_none,
  5, 71, :_reduce_none,
  5, 72, :_reduce_none,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  3, 73, :_reduce_none,
  2, 73, :_reduce_none,
  2, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  1, 59, :_reduce_66,
  1, 59, :_reduce_67,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 77, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 65, :_reduce_73 ]

racc_reduce_n = 74

racc_shift_n = 170

racc_token_table = {
  false => 0,
  :error => 1,
  "program" => 2,
  "end" => 3,
  "read" => 4,
  "write" => 5,
  "writeln" => 6,
  "with" => 7,
  "do" => 8,
  "if" => 9,
  "then" => 10,
  "else" => 11,
  "while" => 12,
  "for" => 13,
  "from" => 14,
  "to" => 15,
  "by" => 16,
  "repeat" => 17,
  "times" => 18,
  "func" => 19,
  "begin" => 20,
  "return" => 21,
  "number" => 22,
  "boolean" => 23,
  "true" => 24,
  "false" => 25,
  "not" => 26,
  "and" => 27,
  "or" => 28,
  "==" => 29,
  "/=" => 30,
  ">=" => 31,
  "<=" => 32,
  ">" => 33,
  "<" => 34,
  "+" => 35,
  "-" => 36,
  "*" => 37,
  "/" => 38,
  "%" => 39,
  "div" => 40,
  "mod" => 41,
  "=" => 42,
  ";" => 43,
  "," => 44,
  "->" => 45,
  "(" => 46,
  ")" => 47,
  :ID => 48,
  :STRING => 49,
  :NUMBER => 50,
  :UMINUS => 51 }

racc_nt_base = 52

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"program\"",
  "\"end\"",
  "\"read\"",
  "\"write\"",
  "\"writeln\"",
  "\"with\"",
  "\"do\"",
  "\"if\"",
  "\"then\"",
  "\"else\"",
  "\"while\"",
  "\"for\"",
  "\"from\"",
  "\"to\"",
  "\"by\"",
  "\"repeat\"",
  "\"times\"",
  "\"func\"",
  "\"begin\"",
  "\"return\"",
  "\"number\"",
  "\"boolean\"",
  "\"true\"",
  "\"false\"",
  "\"not\"",
  "\"and\"",
  "\"or\"",
  "\"==\"",
  "\"/=\"",
  "\">=\"",
  "\"<=\"",
  "\">\"",
  "\"<\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"div\"",
  "\"mod\"",
  "\"=\"",
  "\";\"",
  "\",\"",
  "\"->\"",
  "\"(\"",
  "\")\"",
  "ID",
  "STRING",
  "NUMBER",
  "UMINUS",
  "$start",
  "ESTRUCTURA",
  "FUNCIONES",
  "PROGRAMA",
  "FUNCION",
  "INSTRUCCION",
  "PARAMETROS",
  "TIPO",
  "BLOQUE",
  "DECLARACION",
  "INSTRUCCIONES",
  "LISTA_DECLARACION",
  "LISTA_ID",
  "VARIABLE",
  "ASIGNACION",
  "SECUENCIACION",
  "ENTRADA",
  "SALIDA",
  "CONDICIONAL",
  "REPETICION_D",
  "REPETICION_I",
  "EXPRESION",
  "ESCRIBIR",
  "COND",
  "LITERAL",
  "LITERAL_NUMBER",
  "LITERAL_BOOLEAN" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.y', 128)
  def _reduce_40(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_41(val, _values, result)
    result = result = val[2]
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

module_eval(<<'.,.,', 'parser.y', 166)
  def _reduce_66(val, _values, result)
    result = "number"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 167)
  def _reduce_67(val, _values, result)
    result = "boolean"
    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

module_eval(<<'.,.,', 'parser.y', 185)
  def _reduce_73(val, _values, result)
    result = Variable.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserRtn
