#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
class ParserRtn < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 192)

load 'MainRtn.rb'
load 'clasesParser.rb'
	
	def initialize(tokens)
		@tokens = tokens
		@yydebug = true
	end 

	def parse
		do_parse
	end

	def next_token
		@tokens.next_token
	end

	
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     6,    37,    38,    39,    12,    13,    40,   154,    44,    43,
    41,     7,    18,    19,    42,   155,    12,    13,    35,    37,
    38,    39,    12,    13,    40,    86,     6,    43,    41,    74,
     5,    92,    42,    45,    18,    19,    35,    15,    10,    37,
    38,    39,    12,    13,    40,    36,     5,    43,    41,    14,
    87,    20,    42,    18,    19,    46,    35,    37,    38,    39,
    12,    13,    40,    36,    47,    43,    41,    18,    19,    48,
    42,    18,    19,    49,    35,    50,    37,    38,    39,    12,
    13,    40,    53,    36,    43,    41,    18,    19,    54,    42,
    56,    57,    58,    35,    37,    38,    39,    12,    13,    40,
    59,    36,    43,    41,    60,    61,    62,    42,    74,    75,
    81,    35,    88,    37,    38,    39,    12,    13,    40,    91,
    36,    43,    41,    93,   113,   113,    42,   115,   118,   119,
    35,    37,    38,    39,    12,    13,    40,   123,    36,    43,
    41,   124,   148,   150,    42,   151,   152,    92,    35,   157,
    37,    38,    39,    12,    13,    40,   158,    36,    43,    41,
   159,   160,   164,    42,   165,   166,   169,    35,    37,    38,
    39,    12,    13,    40,   173,    36,    43,    41,   175,   nil,
   nil,    42,   nil,   nil,   nil,    35,   nil,    37,    38,    39,
    12,    13,    40,   nil,    36,    43,    41,   nil,   nil,   nil,
    42,   nil,   nil,   nil,    35,    37,    38,    39,    12,    13,
    40,   nil,    36,    43,    41,   nil,   nil,   nil,    42,   nil,
   nil,   nil,    35,   nil,    37,    38,    39,    12,    13,    40,
   nil,    36,    43,    41,   117,   nil,   nil,    42,   nil,   nil,
   nil,    35,    94,    95,    96,    97,    98,   nil,   nil,    36,
   nil,   nil,   nil,   107,   108,   101,   102,   103,   104,   105,
   106,    99,   100,    94,    95,    96,    97,    98,    36,   168,
    94,    95,    96,    97,    98,   nil,   nil,   167,   nil,   nil,
   nil,   nil,   nil,   nil,   172,   nil,   nil,   nil,   107,   108,
   101,   102,   103,   104,   105,   106,    99,   100,    94,    95,
    96,    97,    98,   107,   108,   101,   102,   103,   104,   105,
   106,    99,   100,    94,    95,    96,    97,    98,   114,   107,
   108,   101,   102,   103,   104,   105,   106,    99,   100,    94,
    95,    96,    97,    98,   nil,   107,   108,   101,   102,   103,
   104,   105,   106,    99,   100,    94,    95,    96,    97,    98,
    72,    73,    67,    72,    73,    67,   nil,   nil,    72,    73,
    67,   nil,    68,   nil,   nil,    68,   nil,   nil,   nil,   nil,
    68,   nil,    66,   nil,    65,    66,    71,    65,    78,    71,
    66,   nil,    65,    78,    71,    72,    73,    67,    72,    73,
    67,    72,    73,    67,    72,    73,    67,    68,   nil,   nil,
    68,   nil,   nil,    68,   nil,   nil,    68,    66,   nil,    65,
    66,    71,    65,    66,    71,    65,    66,    71,    65,   nil,
    71,    72,    73,    67,    72,    73,    67,    72,    73,    67,
    72,    73,    67,    68,   nil,   nil,    68,   nil,   nil,    68,
   nil,   nil,    68,    66,   nil,    65,    66,    71,    65,    66,
    71,    65,    66,    71,    65,   nil,    71,    72,    73,    67,
    72,    73,    67,    72,    73,    67,    72,    73,    67,    68,
   nil,   nil,    68,   nil,   nil,    68,   nil,   nil,    68,    66,
   nil,    65,    66,    71,    65,    66,    71,    65,    66,    71,
    65,   nil,    71,    72,    73,    67,    72,    73,    67,    72,
    73,    67,    72,    73,    67,    68,   nil,   nil,    68,   nil,
   nil,    68,   nil,   nil,    68,    66,   nil,    65,    66,    71,
    65,    66,    71,    65,    66,    71,    65,   nil,    71,    72,
    73,    67,    72,    73,    67,    72,    73,    67,    72,    73,
    67,    68,   nil,   nil,    68,   nil,   nil,    68,   nil,   nil,
    68,    66,   nil,    65,    66,    71,    65,    66,    71,    65,
    66,    71,    65,   nil,    71,    72,    73,    67,    72,    73,
    67,    72,    73,    67,   nil,   nil,   nil,    68,   nil,   nil,
    68,   nil,   nil,    68,   nil,   nil,   nil,    66,   nil,    65,
    66,    71,    65,    66,    71,    65,   143,    71,    72,    73,
    67,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    68,   nil,   nil,   156,   nil,   nil,   nil,   nil,   nil,   nil,
    66,   nil,    65,   nil,    71,   107,   108,   101,   102,   103,
   104,   105,   106,    99,   100,    94,    95,    96,    97,    98,
    72,    73,    67,    72,    73,    67,   nil,   nil,   nil,   nil,
   nil,   nil,    68,   nil,   nil,    68,   nil,   nil,   nil,   nil,
   nil,   116,    66,   nil,    65,    66,    71,    65,   nil,    71,
   107,   108,   101,   102,   103,   104,   105,   106,    99,   100,
    94,    95,    96,    97,    98,   107,   108,   101,   102,   103,
   104,   105,   106,    99,   100,    94,    95,    96,    97,    98,
   nil,   nil,   nil,   nil,   nil,   141,   107,   108,   101,   102,
   103,   104,   105,   106,    99,   100,    94,    95,    96,    97,
    98,   107,   108,   101,   102,   103,   104,   105,   106,    99,
   100,    94,    95,    96,    97,    98,   107,   nil,   101,   102,
   103,   104,   105,   106,    99,   100,    94,    95,    96,    97,
    98,   107,   108,   101,   102,   103,   104,   105,   106,    99,
   100,    94,    95,    96,    97,    98,   -74,   -74,   -74,   -74,
   -74,   -74,    99,   100,    94,    95,    96,    97,    98,   -74,
   -74,   -74,   -74,   -74,   -74,    99,   100,    94,    95,    96,
    97,    98,   -74,   -74,   -74,   -74,   -74,   -74,    99,   100,
    94,    95,    96,    97,    98,   -74,   -74,   -74,   -74,   -74,
   -74,    99,   100,    94,    95,    96,    97,    98,   -74,   -74,
   -74,   -74,   -74,   -74,    99,   100,    94,    95,    96,    97,
    98,   -74,   -74,   -74,   -74,   -74,   -74,    99,   100,    94,
    95,    96,    97,    98,   101,   102,   103,   104,   105,   106,
    99,   100,    94,    95,    96,    97,    98 ]

racc_action_check = [
     0,    13,    13,    13,    13,    13,    13,   144,    15,    13,
    13,     1,    10,    10,    13,   144,     6,     6,    13,    26,
    26,    26,    26,    26,    26,    46,     2,    26,    26,    53,
     4,    53,    26,    15,    12,    12,    26,    10,     5,    44,
    44,    44,    44,    44,    44,    13,     0,    44,    44,     7,
    46,    11,    44,    45,    45,    16,    44,    49,    49,    49,
    49,    49,    49,    26,    17,    49,    49,    50,    50,    20,
    49,    87,    87,    21,    49,    22,    86,    86,    86,    86,
    86,    86,    23,    44,    86,    86,    88,    88,    24,    86,
    27,    28,    29,    86,   114,   114,   114,   114,   114,   114,
    30,    49,   114,   114,    31,    32,    33,   114,    36,    37,
    41,   114,    47,   116,   116,   116,   116,   116,   116,    51,
    86,   116,   116,    54,    76,    79,   116,    81,    84,    85,
   116,   117,   117,   117,   117,   117,   117,    89,   114,   117,
   117,    92,   118,   120,   117,   121,   123,   124,   117,   146,
   119,   119,   119,   119,   119,   119,   147,   116,   119,   119,
   149,   150,   159,   119,   161,   162,   165,   119,   151,   151,
   151,   151,   151,   151,   171,   117,   151,   151,   174,   nil,
   nil,   151,   nil,   nil,   nil,   151,   nil,   155,   155,   155,
   155,   155,   155,   nil,   119,   155,   155,   nil,   nil,   nil,
   155,   nil,   nil,   nil,   155,   168,   168,   168,   168,   168,
   168,   nil,   151,   168,   168,   nil,   nil,   nil,   168,   nil,
   nil,   nil,   168,   nil,   172,   172,   172,   172,   172,   172,
   nil,   155,   172,   172,    83,   nil,   nil,   172,   nil,   nil,
   nil,   172,   131,   131,   131,   131,   131,   nil,   nil,   168,
   nil,   nil,   nil,    83,    83,    83,    83,    83,    83,    83,
    83,    83,    83,    83,    83,    83,    83,    83,   172,   163,
   132,   132,   132,   132,   132,   nil,   nil,   163,   nil,   nil,
   nil,   nil,   nil,   nil,   170,   nil,   nil,   nil,   163,   163,
   163,   163,   163,   163,   163,   163,   163,   163,   163,   163,
   163,   163,   163,   170,   170,   170,   170,   170,   170,   170,
   170,   170,   170,   170,   170,   170,   170,   170,    80,    63,
    63,    63,    63,    63,    63,    63,    63,    63,    63,    63,
    63,    63,    63,    63,   nil,    80,    80,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,    80,    80,
    35,    35,    35,    38,    38,    38,   nil,   nil,    39,    39,
    39,   nil,    35,   nil,   nil,    38,   nil,   nil,   nil,   nil,
    39,   nil,    35,   nil,    35,    38,    35,    38,    38,    38,
    39,   nil,    39,    39,    39,    40,    40,    40,    42,    42,
    42,    43,    43,    43,    66,    66,    66,    40,   nil,   nil,
    42,   nil,   nil,    43,   nil,   nil,    66,    40,   nil,    40,
    42,    40,    42,    43,    42,    43,    66,    43,    66,   nil,
    66,    67,    67,    67,    68,    68,    68,    74,    74,    74,
    94,    94,    94,    67,   nil,   nil,    68,   nil,   nil,    74,
   nil,   nil,    94,    67,   nil,    67,    68,    67,    68,    74,
    68,    74,    94,    74,    94,   nil,    94,    95,    95,    95,
    96,    96,    96,    97,    97,    97,    98,    98,    98,    95,
   nil,   nil,    96,   nil,   nil,    97,   nil,   nil,    98,    95,
   nil,    95,    96,    95,    96,    97,    96,    97,    98,    97,
    98,   nil,    98,    99,    99,    99,   100,   100,   100,   101,
   101,   101,   102,   102,   102,    99,   nil,   nil,   100,   nil,
   nil,   101,   nil,   nil,   102,    99,   nil,    99,   100,    99,
   100,   101,   100,   101,   102,   101,   102,   nil,   102,   103,
   103,   103,   104,   104,   104,   105,   105,   105,   106,   106,
   106,   103,   nil,   nil,   104,   nil,   nil,   105,   nil,   nil,
   106,   103,   nil,   103,   104,   103,   104,   105,   104,   105,
   106,   105,   106,   nil,   106,   107,   107,   107,   108,   108,
   108,   113,   113,   113,   nil,   nil,   nil,   107,   nil,   nil,
   108,   nil,   nil,   113,   nil,   nil,   nil,   107,   nil,   107,
   108,   107,   108,   113,   108,   113,   113,   113,   115,   115,
   115,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   115,   nil,   nil,   145,   nil,   nil,   nil,   nil,   nil,   nil,
   115,   nil,   115,   nil,   115,   145,   145,   145,   145,   145,
   145,   145,   145,   145,   145,   145,   145,   145,   145,   145,
   156,   156,   156,   167,   167,   167,   nil,   nil,   nil,   nil,
   nil,   nil,   156,   nil,   nil,   167,   nil,   nil,   nil,   nil,
   nil,    82,   156,   nil,   156,   167,   156,   167,   nil,   167,
    82,    82,    82,    82,    82,    82,    82,    82,    82,    82,
    82,    82,    82,    82,    82,   109,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
   nil,   nil,   nil,   nil,   nil,   109,    77,    77,    77,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    77,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   112,   112,   112,   112,   112,   112,   140,   nil,   140,   140,
   140,   140,   140,   140,   140,   140,   140,   140,   140,   140,
   140,   142,   142,   142,   142,   142,   142,   142,   142,   142,
   142,   142,   142,   142,   142,   142,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133,   133,   133,   134,
   134,   134,   134,   134,   134,   134,   134,   134,   134,   134,
   134,   134,   135,   135,   135,   135,   135,   135,   135,   135,
   135,   135,   135,   135,   135,   136,   136,   136,   136,   136,
   136,   136,   136,   136,   136,   136,   136,   136,   137,   137,
   137,   137,   137,   137,   137,   137,   137,   137,   137,   137,
   137,   138,   138,   138,   138,   138,   138,   138,   138,   138,
   138,   138,   138,   138,   139,   139,   139,   139,   139,   139,
   139,   139,   139,   139,   139,   139,   139 ]

racc_action_pointer = [
    -2,    11,    24,   nil,   -18,    -8,     9,    49,   nil,   nil,
   -10,    48,    12,    -3,   nil,   -12,     8,    16,   nil,   nil,
    26,    65,    32,    34,    85,   nil,    15,    47,    48,    49,
    57,    61,    62,    63,   nil,   326,    66,    61,   329,   334,
   361,    62,   364,   367,    35,    31,     5,    68,   nil,    53,
    45,    76,   nil,   -13,    80,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   292,   nil,   nil,   370,   397,   400,   nil,
   nil,   nil,   nil,   nil,   403,   nil,    80,   679,   nil,    81,
   308,   113,   643,   226,   125,   109,    72,    49,    64,   134,
   nil,   nil,    93,   nil,   406,   433,   436,   439,   442,   469,
   472,   475,   478,   505,   508,   511,   514,   541,   544,   658,
   nil,   nil,   694,   547,    90,   574,   109,   127,    99,   146,
   140,   125,   nil,   103,   103,   nil,   nil,   nil,   nil,   nil,
   nil,   205,   233,   737,   750,   763,   776,   789,   802,   815,
   709,   nil,   724,   nil,     4,   598,   146,   153,   nil,   157,
   118,   164,   nil,   nil,   nil,   183,   616,   nil,   nil,   119,
   nil,   161,   162,   261,   nil,   123,   nil,   619,   201,   nil,
   276,   171,   220,   nil,   175,   nil ]

racc_action_default = [
   -74,   -74,   -74,    -2,    -4,   -74,   -74,   -74,    -1,    -3,
   -74,   -74,   -74,   -74,   176,   -74,   -74,   -74,   -67,   -68,
   -74,   -74,   -74,   -74,   -74,   -20,   -21,   -74,   -74,   -74,
   -74,   -74,   -74,   -74,   -30,   -74,   -74,   -74,   -74,   -74,
   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -10,   -11,   -74,
   -15,   -74,   -17,   -18,   -74,   -22,   -23,   -24,   -25,   -26,
   -27,   -28,   -29,   -31,   -47,   -48,   -74,   -74,   -74,   -69,
   -70,   -71,   -72,   -73,   -74,   -33,   -34,   -36,   -37,   -35,
   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -14,   -16,   -74,   -13,   -74,   -74,   -74,   -74,   -74,   -74,
   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -50,   -51,   -32,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -74,   -74,    -9,   -74,   -18,   -19,   -52,   -53,   -54,   -55,
   -56,   -57,   -58,   -59,   -60,   -61,   -62,   -63,   -64,   -65,
   -66,   -49,   -38,   -39,   -74,   -74,   -74,   -74,    -5,   -74,
   -74,   -74,   -12,   -40,   -41,   -74,   -74,   -45,   -46,   -74,
    -6,   -74,   -74,   -74,    -7,   -74,   -42,   -74,   -74,    -8,
   -74,   -74,   -74,   -44,   -74,   -43 ]

racc_goto_table = [
    24,    51,   144,    21,     2,     3,     1,     8,     9,    76,
    79,    16,    11,    55,    52,    63,   153,    23,   nil,   nil,
    80,   nil,    82,    83,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    84,   nil,   nil,   nil,   nil,    89,   nil,   nil,   nil,
   nil,    90,   nil,   162,   nil,   nil,   109,   110,   111,   nil,
    85,   nil,   nil,   nil,   112,    23,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   125,   nil,   nil,   120,   126,   127,   128,   129,   130,   131,
   132,   133,   134,   135,   136,   137,   138,   139,   140,   122,
   nil,   nil,   121,   142,   nil,   145,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   146,   147,   nil,   149,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   163,   nil,   161,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   170,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   171,   nil,   nil,   nil,   174 ]

racc_goto_check = [
     5,    11,    14,     9,     2,     3,     1,     3,     2,    22,
    22,     6,     8,     5,    12,    21,    23,     7,   nil,   nil,
    21,   nil,    21,    21,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     5,   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,
   nil,     9,   nil,    14,   nil,   nil,    21,    21,    21,   nil,
     7,   nil,   nil,   nil,    21,     7,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    11,   nil,   nil,     5,    21,    21,    21,    21,    21,    21,
    21,    21,    21,    21,    21,    21,    21,    21,    21,     6,
   nil,   nil,     7,    21,   nil,    21,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5,     5,   nil,     5,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,     5,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     5,   nil,   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,     6,     4,     5,   nil,   -13,     1,     5,     6,    -9,
   nil,   -22,    -9,   nil,  -112,   nil,   nil,   nil,   nil,   nil,
   nil,   -20,   -29,  -128,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,   nil,   nil,    17,    34,   nil,
    22,   nil,    27,    25,    26,    28,    29,    30,    31,    32,
    33,    77,   nil,   nil,    64,    69,    70 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 53, :_reduce_1,
  1, 53, :_reduce_2,
  2, 54, :_reduce_3,
  1, 54, :_reduce_4,
  7, 56, :_reduce_5,
  8, 56, :_reduce_6,
  9, 56, :_reduce_7,
  10, 56, :_reduce_8,
  4, 58, :_reduce_9,
  2, 58, :_reduce_10,
  4, 55, :_reduce_11,
  6, 60, :_reduce_12,
  4, 60, :_reduce_13,
  3, 61, :_reduce_14,
  2, 61, :_reduce_15,
  3, 62, :_reduce_16,
  2, 62, :_reduce_17,
  1, 63, :_reduce_18,
  3, 63, :_reduce_19,
  1, 57, :_reduce_20,
  1, 57, :_reduce_21,
  2, 65, :_reduce_22,
  2, 66, :_reduce_23,
  2, 66, :_reduce_24,
  2, 66, :_reduce_25,
  2, 66, :_reduce_26,
  2, 66, :_reduce_27,
  2, 66, :_reduce_28,
  2, 66, :_reduce_29,
  1, 66, :_reduce_30,
  2, 72, :_reduce_31,
  3, 64, :_reduce_32,
  2, 67, :_reduce_33,
  2, 68, :_reduce_34,
  2, 68, :_reduce_35,
  1, 74, :_reduce_36,
  1, 74, :_reduce_37,
  3, 74, :_reduce_38,
  3, 74, :_reduce_39,
  5, 69, :_reduce_40,
  1, 75, :_reduce_41,
  3, 75, :_reduce_42,
  11, 70, :_reduce_43,
  9, 70, :_reduce_44,
  5, 70, :_reduce_45,
  5, 71, :_reduce_46,
  1, 73, :_reduce_none,
  1, 73, :_reduce_48,
  3, 73, :_reduce_49,
  2, 73, :_reduce_50,
  2, 73, :_reduce_51,
  3, 73, :_reduce_52,
  3, 73, :_reduce_53,
  3, 73, :_reduce_54,
  3, 73, :_reduce_55,
  3, 73, :_reduce_56,
  3, 73, :_reduce_57,
  3, 73, :_reduce_58,
  3, 73, :_reduce_59,
  3, 73, :_reduce_60,
  3, 73, :_reduce_61,
  3, 73, :_reduce_62,
  3, 73, :_reduce_63,
  3, 73, :_reduce_64,
  3, 73, :_reduce_65,
  3, 73, :_reduce_66,
  1, 59, :_reduce_67,
  1, 59, :_reduce_68,
  1, 76, :_reduce_none,
  1, 76, :_reduce_none,
  1, 77, :_reduce_71,
  1, 78, :_reduce_72,
  1, 78, :_reduce_73 ]

racc_reduce_n = 74

racc_shift_n = 176

racc_token_table = {
  false => 0,
  :error => 1,
  "program" => 2,
  "end" => 3,
  "read" => 4,
  "write" => 5,
  "writeln" => 6,
  "with" => 7,
  "do" => 8,
  "if" => 9,
  "then" => 10,
  "else" => 11,
  "while" => 12,
  "for" => 13,
  "from" => 14,
  "to" => 15,
  "by" => 16,
  "repeat" => 17,
  "times" => 18,
  "func" => 19,
  "begin" => 20,
  "return" => 21,
  "number" => 22,
  "boolean" => 23,
  "true" => 24,
  "false" => 25,
  "not" => 26,
  "and" => 27,
  "or" => 28,
  "==" => 29,
  "/=" => 30,
  ">=" => 31,
  "<=" => 32,
  ">" => 33,
  "<" => 34,
  "+" => 35,
  "-" => 36,
  "*" => 37,
  "/" => 38,
  "%" => 39,
  "div" => 40,
  "mod" => 41,
  "=" => 42,
  ";" => 43,
  "," => 44,
  "->" => 45,
  "(" => 46,
  ")" => 47,
  :ID => 48,
  :STRING => 49,
  :NUMBER => 50,
  :UMINUS => 51 }

racc_nt_base = 52

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"program\"",
  "\"end\"",
  "\"read\"",
  "\"write\"",
  "\"writeln\"",
  "\"with\"",
  "\"do\"",
  "\"if\"",
  "\"then\"",
  "\"else\"",
  "\"while\"",
  "\"for\"",
  "\"from\"",
  "\"to\"",
  "\"by\"",
  "\"repeat\"",
  "\"times\"",
  "\"func\"",
  "\"begin\"",
  "\"return\"",
  "\"number\"",
  "\"boolean\"",
  "\"true\"",
  "\"false\"",
  "\"not\"",
  "\"and\"",
  "\"or\"",
  "\"==\"",
  "\"/=\"",
  "\">=\"",
  "\"<=\"",
  "\">\"",
  "\"<\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"div\"",
  "\"mod\"",
  "\"=\"",
  "\";\"",
  "\",\"",
  "\"->\"",
  "\"(\"",
  "\")\"",
  "ID",
  "STRING",
  "NUMBER",
  "UMINUS",
  "$start",
  "ESTRUCTURA",
  "FUNCIONES",
  "PROGRAMA",
  "FUNCION",
  "INSTRUCCIONES",
  "PARAMETROS",
  "TIPO",
  "BLOQUE",
  "LISTA_DECLARACION",
  "DECLARACION",
  "LISTA_ID",
  "ASIGNACION",
  "SECUENCIACION",
  "INSTRUCCION",
  "ENTRADA",
  "SALIDA",
  "CONDICIONAL",
  "REPETICION_D",
  "REPETICION_I",
  "RETURN",
  "EXPRESION",
  "ESCRIBIR",
  "COND",
  "LITERAL",
  "LITERAL_NUMBER",
  "LITERAL_BOOLEAN" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_1(val, _values, result)
     result = Estructura.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_2(val, _values, result)
     result = Estructura.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_3(val, _values, result)
     result = Funcion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 45)
  def _reduce_4(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_5(val, _values, result)
     result = Funcion.new(val[0], nil, nil, val[4], nil, nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_6(val, _values, result)
     result = Funcion.new(val[0], val[2], nil, val[6]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_7(val, _values, result)
     result = Funcion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_8(val, _values, result)
     result = Funcion.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_9(val, _values, result)
     result = Parametros.new(val[0],val[1],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_10(val, _values, result)
     result = Parametros.new(val[0],val[1],nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_11(val, _values, result)
     result = Programa.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_12(val, _values, result)
     result = Bloque.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_13(val, _values, result)
     result = Bloque.new(nil, val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_14(val, _values, result)
     result = ListaDeclaracion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_15(val, _values, result)
     result = ListaDeclaracion.new(val[0], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_16(val, _values, result)
     result = Declaracion.new(val[0], val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 76)
  def _reduce_17(val, _values, result)
     result = Declaracion.new(val[0], nil, val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_18(val, _values, result)
     result = Identificador.new(val[0], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_19(val, _values, result)
     result = Identificador.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_20(val, _values, result)
     result = Secuenciacion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_21(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_22(val, _values, result)
     result = Instruccion.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_23(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 94)
  def _reduce_24(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_25(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 96)
  def _reduce_26(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 97)
  def _reduce_27(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_28(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_29(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_30(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 103)
  def _reduce_31(val, _values, result)
     result = Return.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 107)
  def _reduce_32(val, _values, result)
     result = Asignacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 111)
  def _reduce_33(val, _values, result)
     result = Entrada.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_34(val, _values, result)
     result = Salida.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 116)
  def _reduce_35(val, _values, result)
     result = Salida.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_36(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 121)
  def _reduce_37(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 122)
  def _reduce_38(val, _values, result)
     result = Escribir.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 123)
  def _reduce_39(val, _values, result)
     result = Escribir.new()
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 127)
  def _reduce_40(val, _values, result)
     result = Condicional.new(val[1],val[3],val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 131)
  def _reduce_41(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 132)
  def _reduce_42(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 136)
  def _reduce_43(val, _values, result)
     result = For.new(val[1], val[3], val[5], val[7], val[9])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 137)
  def _reduce_44(val, _values, result)
     result = For.new(val[1], val[3], val[5], nil, val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 138)
  def _reduce_45(val, _values, result)
     result = Repeat.new(val[1],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_46(val, _values, result)
     result = RepeticionI.new(val[1],val[3]) 
    result
  end
.,.,

# reduce 47 omitted

module_eval(<<'.,.,', 'parser.y', 147)
  def _reduce_48(val, _values, result)
     result = Identificador.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 148)
  def _reduce_49(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 149)
  def _reduce_50(val, _values, result)
     result = OpNot.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 150)
  def _reduce_51(val, _values, result)
     result = OpUMINUS.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 151)
  def _reduce_52(val, _values, result)
     result = OpMultiplicacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 152)
  def _reduce_53(val, _values, result)
     result = OpDivisionE.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 153)
  def _reduce_54(val, _values, result)
     result = OpModE.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 154)
  def _reduce_55(val, _values, result)
     result = OpDivision.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 155)
  def _reduce_56(val, _values, result)
     result = OpMod.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 156)
  def _reduce_57(val, _values, result)
     result = OpSuma.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 157)
  def _reduce_58(val, _values, result)
     result = OpResta.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 158)
  def _reduce_59(val, _values, result)
     result = OpEquivalente.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 159)
  def _reduce_60(val, _values, result)
     result = OpDesigual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_61(val, _values, result)
     result = OpMayorIgual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 161)
  def _reduce_62(val, _values, result)
     result = OpMenorIgual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_63(val, _values, result)
     result = OpMayor.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 163)
  def _reduce_64(val, _values, result)
     result = OpMenor.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 164)
  def _reduce_65(val, _values, result)
     result = OpAnd.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_66(val, _values, result)
     result = OpOr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 169)
  def _reduce_67(val, _values, result)
     result = TipoNumber.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 170)
  def _reduce_68(val, _values, result)
     result = TipoBoolean.new() 
    result
  end
.,.,

# reduce 69 omitted

# reduce 70 omitted

module_eval(<<'.,.,', 'parser.y', 179)
  def _reduce_71(val, _values, result)
     result = LiteralNumerico.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 183)
  def _reduce_72(val, _values, result)
     result = LiteralBooleano.new("true") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 184)
  def _reduce_73(val, _values, result)
     result = LiteralBooleano.new("false") 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserRtn
