#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
class ParserRtn < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 192)

load 'MainRtn.rb'
load 'clasesParser.rb'
	
	def initialize(tokens)
		@tokens = tokens
		@yydebug = true
	end 

	def parse
		do_parse
	end

	def next_token
		@tokens.next_token
	end

	
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     6,   145,    50,    34,    35,    36,    12,    13,    37,   146,
     7,    40,    38,    12,    13,     6,    39,   116,    34,    35,
    36,    12,    13,    37,    18,    19,    40,    38,    18,    19,
     5,    39,    18,    19,   148,    34,    35,    36,    12,    13,
    37,    84,    85,    40,    38,    10,     5,    33,    39,   149,
    34,    35,    36,    12,    13,    37,    14,    15,    40,    38,
    58,    86,    33,    39,   164,    34,    35,    36,    12,    13,
    37,    41,    20,    40,    38,    18,    19,    43,    39,    33,
    44,   166,    34,    35,    36,    12,    13,    37,    18,    19,
    40,    38,    80,    45,    33,    39,    42,    34,    35,    36,
    12,    13,    37,    46,    48,    40,    38,    52,    53,    33,
    39,    34,    35,    36,    12,    13,    37,    81,    54,    40,
    38,    55,    56,    57,    39,    58,    33,    34,    35,    36,
    12,    13,    37,    59,    75,    40,    38,    82,    87,    89,
    39,    33,    89,    34,    35,    36,    12,    13,    37,   108,
   111,    40,    38,   112,   117,    33,    39,    34,    35,    36,
    12,    13,    37,   139,   141,    40,    38,   142,   143,   150,
    39,    33,    34,    35,    36,    12,    13,    37,   151,   155,
    40,    38,   156,   157,   160,    39,   nil,    33,   nil,    34,
    35,    36,    12,    13,    37,   nil,   nil,    40,    38,   nil,
   nil,    33,    39,   nil,    34,    35,    36,    12,    13,    37,
   nil,   nil,    40,    38,   nil,   nil,    33,    39,    34,    35,
    36,    12,    13,    37,   nil,   nil,    40,    38,   nil,   nil,
   nil,    39,   nil,    33,    34,    35,    36,    12,    13,    37,
   nil,   nil,    40,    38,   nil,   nil,   nil,    39,    33,   nil,
    34,    35,    36,    12,    13,    37,   nil,   nil,    40,    38,
   110,   nil,    33,    39,    34,    35,    36,    12,    13,    37,
   nil,   nil,    40,    38,    70,    71,    65,    39,    33,   103,
   104,    97,    98,    99,   100,   101,   102,    95,    96,    90,
    91,    92,    93,    94,    33,   159,   nil,   nil,    72,    62,
    69,    66,   nil,   158,   nil,   nil,   nil,   nil,    33,   nil,
   163,   nil,   nil,   nil,   103,   104,    97,    98,    99,   100,
   101,   102,    95,    96,    90,    91,    92,    93,    94,   103,
   104,    97,    98,    99,   100,   101,   102,    95,    96,    90,
    91,    92,    93,    94,   107,    90,    91,    92,    93,    94,
   nil,   nil,    70,    71,    65,   nil,    70,    71,    65,   nil,
   nil,   103,   104,    97,    98,    99,   100,   101,   102,    95,
    96,    90,    91,    92,    93,    94,    72,    62,    69,    66,
    72,   nil,    69,    66,    70,    71,    65,   nil,    70,    71,
    65,   nil,    70,    71,    65,   nil,    70,    71,    65,   nil,
    70,    71,    65,   nil,    70,    71,    65,   nil,    72,   nil,
    69,    66,    72,   nil,    69,    66,    72,   nil,    69,    66,
    72,   nil,    69,    66,    72,   nil,    69,    66,    72,   119,
    69,    66,    70,    71,    65,   nil,    70,    71,    65,   nil,
    70,    71,    65,   nil,    70,    71,    65,   nil,    70,    71,
    65,   nil,    70,    71,    65,   nil,    72,   nil,    69,    66,
    72,   nil,    69,    66,    72,   nil,    69,    66,    72,   nil,
    69,    66,    72,   nil,    69,    66,    72,   nil,    69,    66,
    70,    71,    65,   nil,    70,    71,    65,   nil,    70,    71,
    65,   nil,    70,    71,    65,   nil,    70,    71,    65,   nil,
    70,    71,    65,   nil,    72,   nil,    69,    66,    72,   nil,
    69,    66,    72,   nil,    69,    66,    72,   nil,    69,    66,
    72,   nil,    69,    66,    72,   nil,    69,    66,    70,    71,
    65,   nil,    70,    71,    65,   nil,    70,    71,    65,   nil,
    70,    71,    65,   nil,    70,    71,    65,   nil,    70,    71,
    65,   nil,    72,   nil,    69,    66,    72,   nil,    69,    66,
    72,   nil,    69,    66,    72,   147,    69,    66,    72,   nil,
    69,    66,    72,   nil,    69,    66,   nil,   103,   104,    97,
    98,    99,   100,   101,   102,    95,    96,    90,    91,    92,
    93,    94,   109,    90,    91,    92,    93,    94,   nil,   nil,
   nil,   103,   104,    97,    98,    99,   100,   101,   102,    95,
    96,    90,    91,    92,    93,    94,   103,   104,    97,    98,
    99,   100,   101,   102,    95,    96,    90,    91,    92,    93,
    94,   103,   104,    97,    98,    99,   100,   101,   102,    95,
    96,    90,    91,    92,    93,    94,   103,   104,    97,    98,
    99,   100,   101,   102,    95,    96,    90,    91,    92,    93,
    94,   103,   nil,    97,    98,    99,   100,   101,   102,    95,
    96,    90,    91,    92,    93,    94,   -73,   -73,   -73,   -73,
   -73,   -73,    95,    96,    90,    91,    92,    93,    94,   -73,
   -73,   -73,   -73,   -73,   -73,    95,    96,    90,    91,    92,
    93,    94,   -73,   -73,   -73,   -73,   -73,   -73,    95,    96,
    90,    91,    92,    93,    94,   -73,   -73,   -73,   -73,   -73,
   -73,    95,    96,    90,    91,    92,    93,    94,   -73,   -73,
   -73,   -73,   -73,   -73,    95,    96,    90,    91,    92,    93,
    94,   -73,   -73,   -73,   -73,   -73,   -73,    95,    96,    90,
    91,    92,    93,    94,    97,    98,    99,   100,   101,   102,
    95,    96,    90,    91,    92,    93,    94 ]

racc_action_check = [
     0,   135,    23,    23,    23,    23,    23,    23,    23,   135,
     1,    23,    23,     6,     6,     2,    23,    83,    83,    83,
    83,    83,    83,    83,    12,    12,    83,    83,    42,    42,
     4,    83,    10,    10,   137,   137,   137,   137,   137,   137,
   137,    47,    47,   137,   137,     5,     0,    23,   137,   138,
   138,   138,   138,   138,   138,   138,     7,    10,   138,   138,
    48,    48,    83,   138,   162,   162,   162,   162,   162,   162,
   162,    15,    11,   162,   162,    81,    81,    16,   162,   137,
    17,   165,   165,   165,   165,   165,   165,   165,    82,    82,
   165,   165,    43,    20,   138,   165,    15,    13,    13,    13,
    13,    13,    13,    21,    22,    13,    13,    26,    27,   162,
    13,    41,    41,    41,    41,    41,    41,    43,    28,    41,
    41,    29,    30,    31,    41,    33,   165,    46,    46,    46,
    46,    46,    46,    34,    38,    46,    46,    44,    50,    60,
    46,    13,    73,    80,    80,    80,    80,    80,    80,    75,
    78,    80,    80,    79,    85,    41,    80,   107,   107,   107,
   107,   107,   107,   111,   113,   107,   107,   114,   116,   140,
   107,    46,   109,   109,   109,   109,   109,   109,   141,   150,
   109,   109,   152,   153,   156,   109,   nil,    80,   nil,   110,
   110,   110,   110,   110,   110,   nil,   nil,   110,   110,   nil,
   nil,   107,   110,   nil,   112,   112,   112,   112,   112,   112,
   nil,   nil,   112,   112,   nil,   nil,   109,   112,   142,   142,
   142,   142,   142,   142,   nil,   nil,   142,   142,   nil,   nil,
   nil,   142,   nil,   110,   146,   146,   146,   146,   146,   146,
   nil,   nil,   146,   146,   nil,   nil,   nil,   146,   112,   nil,
   159,   159,   159,   159,   159,   159,   nil,   nil,   159,   159,
    77,   nil,   142,   159,   163,   163,   163,   163,   163,   163,
   nil,   nil,   163,   163,    35,    35,    35,   163,   146,    77,
    77,    77,    77,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    77,    77,   159,   154,   nil,   nil,    35,    35,
    35,    35,   nil,   154,   nil,   nil,   nil,   nil,   163,   nil,
   161,   nil,   nil,   nil,   154,   154,   154,   154,   154,   154,
   154,   154,   154,   154,   154,   154,   154,   154,   154,   161,
   161,   161,   161,   161,   161,   161,   161,   161,   161,   161,
   161,   161,   161,   161,    74,   125,   125,   125,   125,   125,
   nil,   nil,    36,    36,    36,   nil,    37,    37,    37,   nil,
   nil,    74,    74,    74,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,    74,    36,    36,    36,    36,
    37,   nil,    37,    37,    39,    39,    39,   nil,    40,    40,
    40,   nil,    58,    58,    58,   nil,    65,    65,    65,   nil,
    66,    66,    66,   nil,    89,    89,    89,   nil,    39,   nil,
    39,    39,    40,   nil,    40,    40,    58,   nil,    58,    58,
    65,   nil,    65,    65,    66,   nil,    66,    66,    89,    89,
    89,    89,    90,    90,    90,   nil,    91,    91,    91,   nil,
    92,    92,    92,   nil,    93,    93,    93,   nil,    94,    94,
    94,   nil,    95,    95,    95,   nil,    90,   nil,    90,    90,
    91,   nil,    91,    91,    92,   nil,    92,    92,    93,   nil,
    93,    93,    94,   nil,    94,    94,    95,   nil,    95,    95,
    96,    96,    96,   nil,    97,    97,    97,   nil,    98,    98,
    98,   nil,    99,    99,    99,   nil,   100,   100,   100,   nil,
   101,   101,   101,   nil,    96,   nil,    96,    96,    97,   nil,
    97,    97,    98,   nil,    98,    98,    99,   nil,    99,    99,
   100,   nil,   100,   100,   101,   nil,   101,   101,   102,   102,
   102,   nil,   103,   103,   103,   nil,   104,   104,   104,   nil,
   108,   108,   108,   nil,   147,   147,   147,   nil,   158,   158,
   158,   nil,   102,   nil,   102,   102,   103,   nil,   103,   103,
   104,   nil,   104,   104,   108,   136,   108,   108,   147,   nil,
   147,   147,   158,   nil,   158,   158,   nil,   136,   136,   136,
   136,   136,   136,   136,   136,   136,   136,   136,   136,   136,
   136,   136,    76,   126,   126,   126,   126,   126,   nil,   nil,
   nil,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,    76,    76,    76,    76,    76,    61,    61,    61,    61,
    61,    61,    61,    61,    61,    61,    61,    61,    61,    61,
    61,    88,    88,    88,    88,    88,    88,    88,    88,    88,
    88,    88,    88,    88,    88,    88,   118,   118,   118,   118,
   118,   118,   118,   118,   118,   118,   118,   118,   118,   118,
   118,   134,   nil,   134,   134,   134,   134,   134,   134,   134,
   134,   134,   134,   134,   134,   134,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   128,
   128,   128,   128,   128,   128,   128,   128,   128,   128,   128,
   128,   128,   129,   129,   129,   129,   129,   129,   129,   129,
   129,   129,   129,   129,   129,   130,   130,   130,   130,   130,
   130,   130,   130,   130,   130,   130,   130,   130,   131,   131,
   131,   131,   131,   131,   131,   131,   131,   131,   131,   131,
   131,   132,   132,   132,   132,   132,   132,   132,   132,   132,
   132,   132,   132,   132,   133,   133,   133,   133,   133,   133,
   133,   133,   133,   133,   133,   133,   133 ]

racc_action_pointer = [
    -2,    10,    13,   nil,   -18,    -1,     6,    56,   nil,   nil,
    10,    69,     2,    93,   nil,    51,    30,    32,   nil,   nil,
    50,    95,    56,    -1,   nil,   nil,    64,    65,    75,    78,
    79,    80,   nil,    83,    85,   250,   328,   332,    86,   360,
   364,   107,     6,    72,    93,   nil,   123,    -2,    18,   nil,
    95,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   368,   nil,
    95,   589,   nil,   nil,   nil,   372,   376,   nil,   nil,   nil,
   nil,   nil,   nil,    98,   334,   135,   574,   252,   147,   133,
   139,    53,    66,    14,   nil,   106,   nil,   nil,   604,   380,
   408,   412,   416,   420,   424,   428,   456,   460,   464,   468,
   472,   476,   504,   508,   512,   nil,   nil,   153,   516,   168,
   185,   120,   200,   161,   147,   nil,   125,   nil,   619,   nil,
   nil,   nil,   nil,   nil,   nil,   308,   556,   647,   660,   673,
   686,   699,   712,   725,   634,    -2,   550,    31,    46,   nil,
   166,   135,   214,   nil,   nil,   nil,   230,   520,   nil,   nil,
   136,   nil,   179,   180,   287,   nil,   141,   nil,   524,   246,
   nil,   302,    61,   260,   nil,    78,   nil ]

racc_action_default = [
   -73,   -73,   -73,    -2,    -4,   -73,   -73,   -73,    -1,    -3,
   -73,   -73,   -73,   -73,   167,   -73,   -73,   -73,   -65,   -66,
   -73,   -73,   -73,   -73,   -21,   -22,   -73,   -73,   -73,   -73,
   -73,   -73,   -30,   -73,   -73,   -73,   -73,   -73,   -73,   -73,
   -73,   -73,   -73,   -73,   -10,   -11,   -73,   -73,   -19,   -18,
   -73,   -23,   -24,   -25,   -26,   -27,   -28,   -29,   -73,   -32,
   -33,   -35,   -36,   -46,   -47,   -73,   -73,   -67,   -68,   -69,
   -70,   -71,   -72,   -34,   -73,   -73,   -73,   -73,   -73,   -73,
   -73,   -73,   -73,   -73,   -16,   -73,   -17,   -13,   -31,   -73,
   -73,   -73,   -73,   -73,   -73,   -73,   -73,   -73,   -73,   -73,
   -73,   -73,   -73,   -73,   -73,   -48,   -49,   -73,   -73,   -73,
   -73,   -73,   -73,   -73,   -73,    -9,   -73,   -20,   -37,   -38,
   -50,   -51,   -52,   -53,   -54,   -55,   -56,   -57,   -58,   -59,
   -60,   -61,   -62,   -63,   -64,   -73,   -73,   -73,   -73,    -5,
   -73,   -73,   -73,   -12,   -39,   -40,   -73,   -73,   -44,   -45,
   -73,    -6,   -73,   -73,   -73,    -7,   -73,   -41,   -73,   -73,
    -8,   -73,   -73,   -73,   -43,   -73,   -42 ]

racc_goto_table = [
    23,    51,     2,     3,     1,     8,     9,    16,    60,    73,
    11,    74,    22,    76,    77,    21,    47,    49,   144,    78,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    88,    83,   nil,   nil,   nil,   nil,   nil,   105,
   106,   nil,    79,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   113,   nil,
   nil,    51,   nil,   118,   120,   121,   122,   123,   124,   125,
   126,   127,   128,   129,   130,   131,   132,   133,   134,   115,
   nil,   114,   136,   nil,   nil,   135,   nil,   nil,   nil,   nil,
   140,   nil,   nil,   nil,   nil,   nil,   137,   138,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    51,    51,   nil,   nil,   nil,
   152,   154,   nil,   nil,   153,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   161,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    51,   nil,   nil,    51,   nil,   nil,   162,   nil,   nil,   nil,
   165 ]

racc_goto_check = [
    10,     5,     2,     3,     1,     3,     2,     6,    21,    21,
     8,    20,     7,    20,    20,     9,    12,    13,    22,     5,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    20,    10,   nil,   nil,   nil,   nil,   nil,    20,
    20,   nil,     7,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     5,   nil,
   nil,     5,   nil,    20,    20,    20,    20,    20,    20,    20,
    20,    20,    20,    20,    20,    20,    20,    20,    20,     6,
   nil,     7,    20,   nil,   nil,     5,   nil,   nil,   nil,   nil,
     5,   nil,   nil,   nil,   nil,   nil,    10,    10,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     5,     5,   nil,   nil,   nil,
     5,    20,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     5,   nil,   nil,     5,   nil,   nil,    10,   nil,   nil,   nil,
    10 ]

racc_goto_pointer = [
   nil,     4,     2,     3,   nil,   -22,    -3,     0,     4,     3,
   -13,   nil,    -6,    -5,   nil,   nil,   nil,   nil,   nil,   nil,
   -26,   -27,  -117,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,    25,   nil,    17,    32,   nil,
   nil,   nil,   nil,    26,    24,    27,    28,    29,    30,    31,
    61,   nil,   nil,    63,    64,    67,    68 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 53, :_reduce_none,
  1, 53, :_reduce_none,
  2, 54, :_reduce_none,
  1, 54, :_reduce_none,
  7, 56, :_reduce_none,
  8, 56, :_reduce_none,
  9, 56, :_reduce_none,
  10, 56, :_reduce_none,
  4, 58, :_reduce_none,
  2, 58, :_reduce_none,
  4, 55, :_reduce_none,
  6, 60, :_reduce_none,
  4, 60, :_reduce_none,
  3, 63, :_reduce_none,
  2, 63, :_reduce_none,
  3, 61, :_reduce_none,
  3, 61, :_reduce_none,
  2, 61, :_reduce_none,
  1, 64, :_reduce_none,
  3, 64, :_reduce_none,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  2, 66, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  2, 57, :_reduce_none,
  1, 57, :_reduce_none,
  3, 65, :_reduce_none,
  2, 67, :_reduce_none,
  2, 68, :_reduce_none,
  2, 68, :_reduce_none,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  3, 73, :_reduce_none,
  3, 73, :_reduce_none,
  5, 69, :_reduce_none,
  1, 74, :_reduce_40,
  3, 74, :_reduce_41,
  11, 70, :_reduce_none,
  9, 70, :_reduce_none,
  5, 70, :_reduce_none,
  5, 71, :_reduce_none,
  1, 72, :_reduce_none,
  1, 72, :_reduce_none,
  2, 72, :_reduce_none,
  2, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  3, 72, :_reduce_none,
  1, 59, :_reduce_65,
  1, 59, :_reduce_66,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 77, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 76, :_reduce_72 ]

racc_reduce_n = 73

racc_shift_n = 167

racc_token_table = {
  false => 0,
  :error => 1,
  "program" => 2,
  "end" => 3,
  "read" => 4,
  "write" => 5,
  "writeln" => 6,
  "with" => 7,
  "do" => 8,
  "if" => 9,
  "then" => 10,
  "else" => 11,
  "while" => 12,
  "for" => 13,
  "from" => 14,
  "to" => 15,
  "by" => 16,
  "repeat" => 17,
  "times" => 18,
  "func" => 19,
  "begin" => 20,
  "return" => 21,
  "number" => 22,
  "boolean" => 23,
  "true" => 24,
  "false" => 25,
  "not" => 26,
  "and" => 27,
  "or" => 28,
  "==" => 29,
  "/=" => 30,
  ">=" => 31,
  "<=" => 32,
  ">" => 33,
  "<" => 34,
  "+" => 35,
  "-" => 36,
  "*" => 37,
  "/" => 38,
  "%" => 39,
  "div" => 40,
  "mod" => 41,
  "=" => 42,
  ";" => 43,
  "," => 44,
  "->" => 45,
  "(" => 46,
  ")" => 47,
  :ID => 48,
  :STRING => 49,
  :NUMBER => 50,
  :UMINUS => 51 }

racc_nt_base = 52

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"program\"",
  "\"end\"",
  "\"read\"",
  "\"write\"",
  "\"writeln\"",
  "\"with\"",
  "\"do\"",
  "\"if\"",
  "\"then\"",
  "\"else\"",
  "\"while\"",
  "\"for\"",
  "\"from\"",
  "\"to\"",
  "\"by\"",
  "\"repeat\"",
  "\"times\"",
  "\"func\"",
  "\"begin\"",
  "\"return\"",
  "\"number\"",
  "\"boolean\"",
  "\"true\"",
  "\"false\"",
  "\"not\"",
  "\"and\"",
  "\"or\"",
  "\"==\"",
  "\"/=\"",
  "\">=\"",
  "\"<=\"",
  "\">\"",
  "\"<\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"div\"",
  "\"mod\"",
  "\"=\"",
  "\";\"",
  "\",\"",
  "\"->\"",
  "\"(\"",
  "\")\"",
  "ID",
  "STRING",
  "NUMBER",
  "UMINUS",
  "$start",
  "ESTRUCTURA",
  "FUNCIONES",
  "PROGRAMA",
  "FUNCION",
  "INSTRUCCION",
  "PARAMETROS",
  "TIPO",
  "BLOQUE",
  "DECLARACION",
  "INSTRUCCIONES",
  "LISTA_DECLARACION",
  "LISTA_ID",
  "ASIGNACION",
  "SECUENCIACION",
  "ENTRADA",
  "SALIDA",
  "CONDICIONAL",
  "REPETICION_D",
  "REPETICION_I",
  "EXPRESION",
  "ESCRIBIR",
  "COND",
  "LITERAL",
  "VARIABLE",
  "LITERAL_NUMBER",
  "LITERAL_BOOLEAN" ]

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.y', 128)
  def _reduce_40(val, _values, result)
    result = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_41(val, _values, result)
    result = result = val[2]
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_65(val, _values, result)
    result = "number"
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 166)
  def _reduce_66(val, _values, result)
    result = "boolean"
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

module_eval(<<'.,.,', 'parser.y', 184)
  def _reduce_72(val, _values, result)
    result = Variable.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserRtn
